SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[usp_getColumnName]
@tblName VARCHAR(500)
AS 
SELECT UPPER(REPLACE(REPLACE(COLUMN_NAME,'_',' '),'dm','')) AS judul,COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = @tblName AND COLUMN_NAME<>'rowid'
ORDER BY ORDINAL_POSITION
GO
