//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDA.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alert_Summary
    {
        public System.DateTime PERIODE { get; set; }
        public long rowid { get; set; }
        public string KODE_ALERT { get; set; }
        public string TIPE_PERIODE { get; set; }
        public string MEMBER_TYPE_CODE { get; set; }
        public string MEMBER_CODE { get; set; }
        public string OFFICE_CODE { get; set; }
        public string DIMENSI1 { get; set; }
        public string DIMENSI2 { get; set; }
        public string DIMENSI3 { get; set; }
        public string DIMENSI4 { get; set; }
        public string DIMENSI5 { get; set; }
        public string LEVEL_ALERT { get; set; }
        public Nullable<decimal> NILAI1 { get; set; }
        public Nullable<decimal> NILAI_PEMBANDING1 { get; set; }
        public Nullable<decimal> NILAI2 { get; set; }
        public Nullable<decimal> NILAI_PEMBANDING2 { get; set; }
        public string stsrc { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
    }
}
