//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDA.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BDA_A01_Cluster
    {
        public long rowid { get; set; }
        public string kode_report { get; set; }
        public System.DateTime periode { get; set; }
        public string member_type_code { get; set; }
        public string member_code { get; set; }
        public string jenis_agunan { get; set; }
        public string status { get; set; }
        public string cluster { get; set; }
        public Nullable<decimal> sum_collateral_value_member { get; set; }
        public Nullable<long> cnt { get; set; }
    }
}
