//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDA.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DataEntities : DbContext
    {
        public DataEntities()
            : base("name=DataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alert_Master> Alert_Master { get; set; }
        public virtual DbSet<Alert_Summary> Alert_Summary { get; set; }
        public virtual DbSet<AuditTrail> AuditTrails { get; set; }
        public virtual DbSet<BDA_A01_Cluster> BDA_A01_Cluster { get; set; }
        public virtual DbSet<BDA_HML_MCDFA> BDA_HML_MCDFA { get; set; }
        public virtual DbSet<BDA_Log_PerHour> BDA_Log_PerHour { get; set; }
        public virtual DbSet<BDA_LogOutliers_Act> BDA_LogOutliers_Act { get; set; }
        public virtual DbSet<BDA2_Table> BDA2_Table { get; set; }
        public virtual DbSet<BDA2_Table_Period> BDA2_Table_Period { get; set; }
        public virtual DbSet<BDA2_Table_Period_LJK> BDA2_Table_Period_LJK { get; set; }
        public virtual DbSet<debitur_anomali_data_populasi> debitur_anomali_data_populasi { get; set; }
        public virtual DbSet<DimTanggal> DimTanggals { get; set; }
        public virtual DbSet<DimTime> DimTimes { get; set; }
        public virtual DbSet<DxReport> DxReports { get; set; }
        public virtual DbSet<Email_In> Email_In { get; set; }
        public virtual DbSet<FWAttachment> FWAttachments { get; set; }
        public virtual DbSet<FWCalendar> FWCalendars { get; set; }
        public virtual DbSet<FWEmailQueue> FWEmailQueues { get; set; }
        public virtual DbSet<FWHoliday> FWHolidays { get; set; }
        public virtual DbSet<FWKodeCounter> FWKodeCounters { get; set; }
        public virtual DbSet<FWKodeDetail> FWKodeDetails { get; set; }
        public virtual DbSet<FWKodeFormat> FWKodeFormats { get; set; }
        public virtual DbSet<FWLOGError> FWLOGErrors { get; set; }
        public virtual DbSet<FWNotice> FWNotices { get; set; }
        public virtual DbSet<FWNoticeQueue> FWNoticeQueues { get; set; }
        public virtual DbSet<FWNoticeTemplate> FWNoticeTemplates { get; set; }
        public virtual DbSet<FWRefModul> FWRefModuls { get; set; }
        public virtual DbSet<FWRefModulMenu> FWRefModulMenus { get; set; }
        public virtual DbSet<FWRefRole> FWRefRoles { get; set; }
        public virtual DbSet<FWRefSetting> FWRefSettings { get; set; }
        public virtual DbSet<FWRoleRight> FWRoleRights { get; set; }
        public virtual DbSet<FWTempTable> FWTempTables { get; set; }
        public virtual DbSet<FWUserLostPassword> FWUserLostPasswords { get; set; }
        public virtual DbSet<FWUserRole> FWUserRoles { get; set; }
        public virtual DbSet<FWWorkday> FWWorkdays { get; set; }
        public virtual DbSet<Help> Helps { get; set; }
        public virtual DbSet<HiveSync> HiveSyncs { get; set; }
        public virtual DbSet<KonfigurasiAlert> KonfigurasiAlerts { get; set; }
        public virtual DbSet<KonfigurasiALertDetail> KonfigurasiALertDetails { get; set; }
        public virtual DbSet<la_inquiry_check> la_inquiry_check { get; set; }
        public virtual DbSet<la_inquiry_pattern_recognition> la_inquiry_pattern_recognition { get; set; }
        public virtual DbSet<LOG_AKSES> LOG_AKSES { get; set; }
        public virtual DbSet<Log_ETL> Log_ETL { get; set; }
        public virtual DbSet<market_driven_ape_growth> market_driven_ape_growth { get; set; }
        public virtual DbSet<market_driven_rg_ng> market_driven_rg_ng { get; set; }
        public virtual DbSet<market_driven_stp_balance> market_driven_stp_balance { get; set; }
        public virtual DbSet<market_driven_stp_settlement_new> market_driven_stp_settlement_new { get; set; }
        public virtual DbSet<Master_Agunan> Master_Agunan { get; set; }
        public virtual DbSet<Master_Keterangan> Master_Keterangan { get; set; }
        public virtual DbSet<master_ljk> master_ljk { get; set; }
        public virtual DbSet<master_ljk_type> master_ljk_type { get; set; }
        public virtual DbSet<master_office_ljk> master_office_ljk { get; set; }
        public virtual DbSet<master_sid> master_sid { get; set; }
        public virtual DbSet<master_user_ideb> master_user_ideb { get; set; }
        public virtual DbSet<MasterKota> MasterKotas { get; set; }
        public virtual DbSet<MasterPenggunaanData> MasterPenggunaanDatas { get; set; }
        public virtual DbSet<MasterPropinsi> MasterPropinsis { get; set; }
        public virtual DbSet<MasterSatker> MasterSatkers { get; set; }
        public virtual DbSet<ml_log_aktivitas> ml_log_aktivitas { get; set; }
        public virtual DbSet<ml_log_mon_data> ml_log_mon_data { get; set; }
        public virtual DbSet<ml_master_log> ml_master_log { get; set; }
        public virtual DbSet<osida_master> osida_master { get; set; }
        public virtual DbSet<osida_nik_tidak_konsisten_det> osida_nik_tidak_konsisten_det { get; set; }
        public virtual DbSet<osida_nik_tidak_konsisten_mst> osida_nik_tidak_konsisten_mst { get; set; }
        public virtual DbSet<osida_pembanding_populasi_chart> osida_pembanding_populasi_chart { get; set; }
        public virtual DbSet<pe_segmentation_basis_investor> pe_segmentation_basis_investor { get; set; }
        public virtual DbSet<pe_segmentation_detail_basis_investor_sre> pe_segmentation_detail_basis_investor_sre { get; set; }
        public virtual DbSet<pe_segmentation_geo> pe_segmentation_geo { get; set; }
        public virtual DbSet<pe_segmentation_pendanaan_per_mkbd> pe_segmentation_pendanaan_per_mkbd { get; set; }
        public virtual DbSet<pe_segmentation_summary_transaction_sid> pe_segmentation_summary_transaction_sid { get; set; }
        public virtual DbSet<Penarikan_Data> Penarikan_Data { get; set; }
        public virtual DbSet<ref_cities> ref_cities { get; set; }
        public virtual DbSet<ref_collateral_types> ref_collateral_types { get; set; }
        public virtual DbSet<ref_credit_types> ref_credit_types { get; set; }
        public virtual DbSet<ref_credit_usages> ref_credit_usages { get; set; }
        public virtual DbSet<ref_ownership_document_temp> ref_ownership_document_temp { get; set; }
        public virtual DbSet<ref_pekerjaan_temp> ref_pekerjaan_temp { get; set; }
        public virtual DbSet<ReportDef> ReportDefs { get; set; }
        public virtual DbSet<RptGrid> RptGrids { get; set; }
        public virtual DbSet<RptGrid_Param> RptGrid_Param { get; set; }
        public virtual DbSet<RptGrid_Queue> RptGrid_Queue { get; set; }
        public virtual DbSet<RptGrid_RoleSetting> RptGrid_RoleSetting { get; set; }
        public virtual DbSet<TableauLink> TableauLinks { get; set; }
        public virtual DbSet<Thread> Threads { get; set; }
        public virtual DbSet<Thread_Post> Thread_Post { get; set; }
        public virtual DbSet<UserMaster> UserMasters { get; set; }
        public virtual DbSet<ip_ownership> ip_ownership { get; set; }
        public virtual DbSet<ip_relation_ownership> ip_relation_ownership { get; set; }
        public virtual DbSet<ip_relation_sid> ip_relation_sid { get; set; }
        public virtual DbSet<ip_relation_transaction> ip_relation_transaction { get; set; }
        public virtual DbSet<ip_sid> ip_sid { get; set; }
        public virtual DbSet<ip_transaction> ip_transaction { get; set; }
        public virtual DbSet<market_driven_ape_growth1> market_driven_ape_growth1 { get; set; }
        public virtual DbSet<market_driven_rg_ng1> market_driven_rg_ng1 { get; set; }
        public virtual DbSet<market_driven_stp_balance1> market_driven_stp_balance1 { get; set; }
        public virtual DbSet<market_driven_stp_settlement_new1> market_driven_stp_settlement_new1 { get; set; }
        public virtual DbSet<mm_spv> mm_spv { get; set; }
        public virtual DbSet<mm_total> mm_total { get; set; }
        public virtual DbSet<pe_segmentation_hutang_subordinasi_det> pe_segmentation_hutang_subordinasi_det { get; set; }
        public virtual DbSet<pe_segmentation_pembiayaan_vs_jaminan_saham> pe_segmentation_pembiayaan_vs_jaminan_saham { get; set; }
        public virtual DbSet<src_sid> src_sid { get; set; }
        public virtual DbSet<pasarmodal_market_driven_rg_ng> pasarmodal_market_driven_rg_ng { get; set; }
        public virtual DbSet<pengawas_ljk> pengawas_ljk { get; set; }
        public virtual DbSet<PM_dimSecurityCompanies> PM_dimSecurityCompanies { get; set; }
        public virtual DbSet<MEMBER_OFFICES> MEMBER_OFFICES { get; set; }
        public virtual DbSet<MEMBER_TYPES> MEMBER_TYPES { get; set; }
        public virtual DbSet<MEMBER> MEMBERS { get; set; }
        public virtual DbSet<dim_exchange_members> dim_exchange_members { get; set; }
        public virtual DbSet<pe_segmentation_bridging_detail> pe_segmentation_bridging_detail { get; set; }
        public virtual DbSet<pe_segmentation_det_jaminan_margin> pe_segmentation_det_jaminan_margin { get; set; }
        public virtual DbSet<pe_segmentation_det_jaminan_margin_sum> pe_segmentation_det_jaminan_margin_sum { get; set; }
        public virtual DbSet<pe_segmentation_det_portofolio_saham> pe_segmentation_det_portofolio_saham { get; set; }
        public virtual DbSet<pe_segmentation_det_portofolio_saham_sum> pe_segmentation_det_portofolio_saham_sum { get; set; }
        public virtual DbSet<pe_segmentation_det_reksa_dana> pe_segmentation_det_reksa_dana { get; set; }
        public virtual DbSet<pe_segmentation_det_reksa_dana_sum> pe_segmentation_det_reksa_dana_sum { get; set; }
        public virtual DbSet<pe_segmentation_det_reverse_repo_new> pe_segmentation_det_reverse_repo_new { get; set; }
        public virtual DbSet<pe_segmentation_det_reverse_repo_sum_new> pe_segmentation_det_reverse_repo_sum_new { get; set; }
        public virtual DbSet<pe_segmentation_sum_cluster_mkbd> pe_segmentation_sum_cluster_mkbd { get; set; }
        public virtual DbSet<vw_getMasterLJK> vw_getMasterLJK { get; set; }
        public virtual DbSet<vw_getMasterOfficeLJK> vw_getMasterOfficeLJK { get; set; }
        public virtual DbSet<vw_JarakAntarAktivitas> vw_JarakAntarAktivitas { get; set; }
        public virtual DbSet<vw_ListUser> vw_ListUser { get; set; }
        public virtual DbSet<vw_Log_Akses> vw_Log_Akses { get; set; }
        public virtual DbSet<vw_Modul> vw_Modul { get; set; }
        public virtual DbSet<vw_PengawasLJK> vw_PengawasLJK { get; set; }
        public virtual DbSet<vw_PeriodTableHive> vw_PeriodTableHive { get; set; }
        public virtual DbSet<vw_RefDeskripsiKategori> vw_RefDeskripsiKategori { get; set; }
        public virtual DbSet<vw_TableDictionary> vw_TableDictionary { get; set; }
    
        [DbFunction("DataEntities", "FT_Modul_Children")]
        public virtual IQueryable<FT_Modul_Children_Result> FT_Modul_Children(string node_id)
        {
            var node_idParameter = node_id != null ?
                new ObjectParameter("node_id", node_id) :
                new ObjectParameter("node_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FT_Modul_Children_Result>("[DataEntities].[FT_Modul_Children](@node_id)", node_idParameter);
        }
    
        [DbFunction("DataEntities", "FT_Satker_Ancestor")]
        public virtual IQueryable<FT_Satker_Ancestor_Result> FT_Satker_Ancestor(Nullable<long> sakterID)
        {
            var sakterIDParameter = sakterID.HasValue ?
                new ObjectParameter("sakterID", sakterID) :
                new ObjectParameter("sakterID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FT_Satker_Ancestor_Result>("[DataEntities].[FT_Satker_Ancestor](@sakterID)", sakterIDParameter);
        }
    
        [DbFunction("DataEntities", "Split")]
        public virtual IQueryable<Split_Result> Split(string sep, string s)
        {
            var sepParameter = sep != null ?
                new ObjectParameter("sep", sep) :
                new ObjectParameter("sep", typeof(string));
    
            var sParameter = s != null ?
                new ObjectParameter("s", s) :
                new ObjectParameter("s", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Split_Result>("[DataEntities].[Split](@sep, @s)", sepParameter, sParameter);
        }
    
        public virtual ObjectResult<FW_userPermission_Result> FW_userPermission(string user_id, string mod_kode, string role_name)
        {
            var user_idParameter = user_id != null ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(string));
    
            var mod_kodeParameter = mod_kode != null ?
                new ObjectParameter("mod_kode", mod_kode) :
                new ObjectParameter("mod_kode", typeof(string));
    
            var role_nameParameter = role_name != null ?
                new ObjectParameter("role_name", role_name) :
                new ObjectParameter("role_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FW_userPermission_Result>("FW_userPermission", user_idParameter, mod_kodeParameter, role_nameParameter);
        }
    
        public virtual int PrintLongString(string str)
        {
            var strParameter = str != null ?
                new ObjectParameter("str", str) :
                new ObjectParameter("str", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PrintLongString", strParameter);
        }
    
        public virtual ObjectResult<usp_calendar_workday_Result> usp_calendar_workday()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_calendar_workday_Result>("usp_calendar_workday");
        }
    
        public virtual int usp_CheckMatchLoginLogoutLog()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_CheckMatchLoginLogoutLog");
        }
    
        public virtual ObjectResult<usp_getAlertSummary_Result> usp_getAlertSummary(string kode_alert, string kode_alert_kategori, string level_alert, string jenis_ljk, string ljk, string office, string periode_awal, string periode_akhir, string datamart, string dimensi1, string dimensi2, string dimensi3, string dimensi4, string dimensi5)
        {
            var kode_alertParameter = kode_alert != null ?
                new ObjectParameter("kode_alert", kode_alert) :
                new ObjectParameter("kode_alert", typeof(string));
    
            var kode_alert_kategoriParameter = kode_alert_kategori != null ?
                new ObjectParameter("kode_alert_kategori", kode_alert_kategori) :
                new ObjectParameter("kode_alert_kategori", typeof(string));
    
            var level_alertParameter = level_alert != null ?
                new ObjectParameter("level_alert", level_alert) :
                new ObjectParameter("level_alert", typeof(string));
    
            var jenis_ljkParameter = jenis_ljk != null ?
                new ObjectParameter("jenis_ljk", jenis_ljk) :
                new ObjectParameter("jenis_ljk", typeof(string));
    
            var ljkParameter = ljk != null ?
                new ObjectParameter("ljk", ljk) :
                new ObjectParameter("ljk", typeof(string));
    
            var officeParameter = office != null ?
                new ObjectParameter("office", office) :
                new ObjectParameter("office", typeof(string));
    
            var periode_awalParameter = periode_awal != null ?
                new ObjectParameter("periode_awal", periode_awal) :
                new ObjectParameter("periode_awal", typeof(string));
    
            var periode_akhirParameter = periode_akhir != null ?
                new ObjectParameter("periode_akhir", periode_akhir) :
                new ObjectParameter("periode_akhir", typeof(string));
    
            var datamartParameter = datamart != null ?
                new ObjectParameter("datamart", datamart) :
                new ObjectParameter("datamart", typeof(string));
    
            var dimensi1Parameter = dimensi1 != null ?
                new ObjectParameter("dimensi1", dimensi1) :
                new ObjectParameter("dimensi1", typeof(string));
    
            var dimensi2Parameter = dimensi2 != null ?
                new ObjectParameter("dimensi2", dimensi2) :
                new ObjectParameter("dimensi2", typeof(string));
    
            var dimensi3Parameter = dimensi3 != null ?
                new ObjectParameter("dimensi3", dimensi3) :
                new ObjectParameter("dimensi3", typeof(string));
    
            var dimensi4Parameter = dimensi4 != null ?
                new ObjectParameter("dimensi4", dimensi4) :
                new ObjectParameter("dimensi4", typeof(string));
    
            var dimensi5Parameter = dimensi5 != null ?
                new ObjectParameter("dimensi5", dimensi5) :
                new ObjectParameter("dimensi5", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_getAlertSummary_Result>("usp_getAlertSummary", kode_alertParameter, kode_alert_kategoriParameter, level_alertParameter, jenis_ljkParameter, ljkParameter, officeParameter, periode_awalParameter, periode_akhirParameter, datamartParameter, dimensi1Parameter, dimensi2Parameter, dimensi3Parameter, dimensi4Parameter, dimensi5Parameter);
        }
    
        public virtual ObjectResult<usp_getAlertSummaryRJPOtherLJK_Result> usp_getAlertSummaryRJPOtherLJK(string member_type_code, string member_code, string member_type_code2, string member_code2, string tipe_periode, string dimensi1, string dimensi2, Nullable<System.DateTime> periode_from, Nullable<System.DateTime> periode_until, string level_alert)
        {
            var member_type_codeParameter = member_type_code != null ?
                new ObjectParameter("member_type_code", member_type_code) :
                new ObjectParameter("member_type_code", typeof(string));
    
            var member_codeParameter = member_code != null ?
                new ObjectParameter("member_code", member_code) :
                new ObjectParameter("member_code", typeof(string));
    
            var member_type_code2Parameter = member_type_code2 != null ?
                new ObjectParameter("member_type_code2", member_type_code2) :
                new ObjectParameter("member_type_code2", typeof(string));
    
            var member_code2Parameter = member_code2 != null ?
                new ObjectParameter("member_code2", member_code2) :
                new ObjectParameter("member_code2", typeof(string));
    
            var tipe_periodeParameter = tipe_periode != null ?
                new ObjectParameter("tipe_periode", tipe_periode) :
                new ObjectParameter("tipe_periode", typeof(string));
    
            var dimensi1Parameter = dimensi1 != null ?
                new ObjectParameter("dimensi1", dimensi1) :
                new ObjectParameter("dimensi1", typeof(string));
    
            var dimensi2Parameter = dimensi2 != null ?
                new ObjectParameter("dimensi2", dimensi2) :
                new ObjectParameter("dimensi2", typeof(string));
    
            var periode_fromParameter = periode_from.HasValue ?
                new ObjectParameter("periode_from", periode_from) :
                new ObjectParameter("periode_from", typeof(System.DateTime));
    
            var periode_untilParameter = periode_until.HasValue ?
                new ObjectParameter("periode_until", periode_until) :
                new ObjectParameter("periode_until", typeof(System.DateTime));
    
            var level_alertParameter = level_alert != null ?
                new ObjectParameter("level_alert", level_alert) :
                new ObjectParameter("level_alert", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_getAlertSummaryRJPOtherLJK_Result>("usp_getAlertSummaryRJPOtherLJK", member_type_codeParameter, member_codeParameter, member_type_code2Parameter, member_code2Parameter, tipe_periodeParameter, dimensi1Parameter, dimensi2Parameter, periode_fromParameter, periode_untilParameter, level_alertParameter);
        }
    
        public virtual ObjectResult<usp_getColumnName_Result> usp_getColumnName(string tblName)
        {
            var tblNameParameter = tblName != null ?
                new ObjectParameter("tblName", tblName) :
                new ObjectParameter("tblName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_getColumnName_Result>("usp_getColumnName", tblNameParameter);
        }
    
        public virtual ObjectResult<usp_GetDataAlert_Result> usp_GetDataAlert(string userID, string lvlAlert, Nullable<System.DateTime> periode, string tipePeriode, string uID)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(string));
    
            var lvlAlertParameter = lvlAlert != null ?
                new ObjectParameter("lvlAlert", lvlAlert) :
                new ObjectParameter("lvlAlert", typeof(string));
    
            var periodeParameter = periode.HasValue ?
                new ObjectParameter("periode", periode) :
                new ObjectParameter("periode", typeof(System.DateTime));
    
            var tipePeriodeParameter = tipePeriode != null ?
                new ObjectParameter("tipePeriode", tipePeriode) :
                new ObjectParameter("tipePeriode", typeof(string));
    
            var uIDParameter = uID != null ?
                new ObjectParameter("uID", uID) :
                new ObjectParameter("uID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetDataAlert_Result>("usp_GetDataAlert", userIDParameter, lvlAlertParameter, periodeParameter, tipePeriodeParameter, uIDParameter);
        }
    
        public virtual int usp_getDataClaPredictive(string periode_awal, string periode_akhir, string jenis_ljk, string ljk, string jenisDebitur, string statusCollectability, string dugaanCollectability)
        {
            var periode_awalParameter = periode_awal != null ?
                new ObjectParameter("periode_awal", periode_awal) :
                new ObjectParameter("periode_awal", typeof(string));
    
            var periode_akhirParameter = periode_akhir != null ?
                new ObjectParameter("periode_akhir", periode_akhir) :
                new ObjectParameter("periode_akhir", typeof(string));
    
            var jenis_ljkParameter = jenis_ljk != null ?
                new ObjectParameter("jenis_ljk", jenis_ljk) :
                new ObjectParameter("jenis_ljk", typeof(string));
    
            var ljkParameter = ljk != null ?
                new ObjectParameter("ljk", ljk) :
                new ObjectParameter("ljk", typeof(string));
    
            var jenisDebiturParameter = jenisDebitur != null ?
                new ObjectParameter("jenisDebitur", jenisDebitur) :
                new ObjectParameter("jenisDebitur", typeof(string));
    
            var statusCollectabilityParameter = statusCollectability != null ?
                new ObjectParameter("statusCollectability", statusCollectability) :
                new ObjectParameter("statusCollectability", typeof(string));
    
            var dugaanCollectabilityParameter = dugaanCollectability != null ?
                new ObjectParameter("dugaanCollectability", dugaanCollectability) :
                new ObjectParameter("dugaanCollectability", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_getDataClaPredictive", periode_awalParameter, periode_akhirParameter, jenis_ljkParameter, ljkParameter, jenisDebiturParameter, statusCollectabilityParameter, dugaanCollectabilityParameter);
        }
    
        public virtual int usp_getDataCluster(string periode_awal, string periode_akhir, string jenis_ljk, string ljk, string jenisAgunan, string cluster, string chart)
        {
            var periode_awalParameter = periode_awal != null ?
                new ObjectParameter("periode_awal", periode_awal) :
                new ObjectParameter("periode_awal", typeof(string));
    
            var periode_akhirParameter = periode_akhir != null ?
                new ObjectParameter("periode_akhir", periode_akhir) :
                new ObjectParameter("periode_akhir", typeof(string));
    
            var jenis_ljkParameter = jenis_ljk != null ?
                new ObjectParameter("jenis_ljk", jenis_ljk) :
                new ObjectParameter("jenis_ljk", typeof(string));
    
            var ljkParameter = ljk != null ?
                new ObjectParameter("ljk", ljk) :
                new ObjectParameter("ljk", typeof(string));
    
            var jenisAgunanParameter = jenisAgunan != null ?
                new ObjectParameter("JenisAgunan", jenisAgunan) :
                new ObjectParameter("JenisAgunan", typeof(string));
    
            var clusterParameter = cluster != null ?
                new ObjectParameter("Cluster", cluster) :
                new ObjectParameter("Cluster", typeof(string));
    
            var chartParameter = chart != null ?
                new ObjectParameter("chart", chart) :
                new ObjectParameter("chart", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_getDataCluster", periode_awalParameter, periode_akhirParameter, jenis_ljkParameter, ljkParameter, jenisAgunanParameter, clusterParameter, chartParameter);
        }
    
        public virtual int usp_getDataMMOverdue(string periode_awal, string periode_akhir, string jenis_ljk, string ljk, string jenisDebitur, string statusCollectability)
        {
            var periode_awalParameter = periode_awal != null ?
                new ObjectParameter("periode_awal", periode_awal) :
                new ObjectParameter("periode_awal", typeof(string));
    
            var periode_akhirParameter = periode_akhir != null ?
                new ObjectParameter("periode_akhir", periode_akhir) :
                new ObjectParameter("periode_akhir", typeof(string));
    
            var jenis_ljkParameter = jenis_ljk != null ?
                new ObjectParameter("jenis_ljk", jenis_ljk) :
                new ObjectParameter("jenis_ljk", typeof(string));
    
            var ljkParameter = ljk != null ?
                new ObjectParameter("ljk", ljk) :
                new ObjectParameter("ljk", typeof(string));
    
            var jenisDebiturParameter = jenisDebitur != null ?
                new ObjectParameter("jenisDebitur", jenisDebitur) :
                new ObjectParameter("jenisDebitur", typeof(string));
    
            var statusCollectabilityParameter = statusCollectability != null ?
                new ObjectParameter("statusCollectability", statusCollectability) :
                new ObjectParameter("statusCollectability", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_getDataMMOverdue", periode_awalParameter, periode_akhirParameter, jenis_ljkParameter, ljkParameter, jenisDebiturParameter, statusCollectabilityParameter);
        }
    
        public virtual ObjectResult<usp_getGroupedAlertSummary_Result> usp_getGroupedAlertSummary(string kode_alert, string kode_alert_kategori, string level_alert, string jenis_ljk, string ljk, string office, string periode_awal, string periode_akhir, string datamart, string dimensi1, string dimensi2, string dimensi3, string dimensi4, string dimensi5)
        {
            var kode_alertParameter = kode_alert != null ?
                new ObjectParameter("kode_alert", kode_alert) :
                new ObjectParameter("kode_alert", typeof(string));
    
            var kode_alert_kategoriParameter = kode_alert_kategori != null ?
                new ObjectParameter("kode_alert_kategori", kode_alert_kategori) :
                new ObjectParameter("kode_alert_kategori", typeof(string));
    
            var level_alertParameter = level_alert != null ?
                new ObjectParameter("level_alert", level_alert) :
                new ObjectParameter("level_alert", typeof(string));
    
            var jenis_ljkParameter = jenis_ljk != null ?
                new ObjectParameter("jenis_ljk", jenis_ljk) :
                new ObjectParameter("jenis_ljk", typeof(string));
    
            var ljkParameter = ljk != null ?
                new ObjectParameter("ljk", ljk) :
                new ObjectParameter("ljk", typeof(string));
    
            var officeParameter = office != null ?
                new ObjectParameter("office", office) :
                new ObjectParameter("office", typeof(string));
    
            var periode_awalParameter = periode_awal != null ?
                new ObjectParameter("periode_awal", periode_awal) :
                new ObjectParameter("periode_awal", typeof(string));
    
            var periode_akhirParameter = periode_akhir != null ?
                new ObjectParameter("periode_akhir", periode_akhir) :
                new ObjectParameter("periode_akhir", typeof(string));
    
            var datamartParameter = datamart != null ?
                new ObjectParameter("datamart", datamart) :
                new ObjectParameter("datamart", typeof(string));
    
            var dimensi1Parameter = dimensi1 != null ?
                new ObjectParameter("dimensi1", dimensi1) :
                new ObjectParameter("dimensi1", typeof(string));
    
            var dimensi2Parameter = dimensi2 != null ?
                new ObjectParameter("dimensi2", dimensi2) :
                new ObjectParameter("dimensi2", typeof(string));
    
            var dimensi3Parameter = dimensi3 != null ?
                new ObjectParameter("dimensi3", dimensi3) :
                new ObjectParameter("dimensi3", typeof(string));
    
            var dimensi4Parameter = dimensi4 != null ?
                new ObjectParameter("dimensi4", dimensi4) :
                new ObjectParameter("dimensi4", typeof(string));
    
            var dimensi5Parameter = dimensi5 != null ?
                new ObjectParameter("dimensi5", dimensi5) :
                new ObjectParameter("dimensi5", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_getGroupedAlertSummary_Result>("usp_getGroupedAlertSummary", kode_alertParameter, kode_alert_kategoriParameter, level_alertParameter, jenis_ljkParameter, ljkParameter, officeParameter, periode_awalParameter, periode_akhirParameter, datamartParameter, dimensi1Parameter, dimensi2Parameter, dimensi3Parameter, dimensi4Parameter, dimensi5Parameter);
        }
    
        public virtual ObjectResult<usp_getGroupedRJPOtherLJK_Result> usp_getGroupedRJPOtherLJK(string member_type_code, string member_code, string member_type_code2, string member_code2, string tipe_periode, string dimensi1, string dimensi2, Nullable<System.DateTime> periode_from, Nullable<System.DateTime> periode_until, string level_alert)
        {
            var member_type_codeParameter = member_type_code != null ?
                new ObjectParameter("member_type_code", member_type_code) :
                new ObjectParameter("member_type_code", typeof(string));
    
            var member_codeParameter = member_code != null ?
                new ObjectParameter("member_code", member_code) :
                new ObjectParameter("member_code", typeof(string));
    
            var member_type_code2Parameter = member_type_code2 != null ?
                new ObjectParameter("member_type_code2", member_type_code2) :
                new ObjectParameter("member_type_code2", typeof(string));
    
            var member_code2Parameter = member_code2 != null ?
                new ObjectParameter("member_code2", member_code2) :
                new ObjectParameter("member_code2", typeof(string));
    
            var tipe_periodeParameter = tipe_periode != null ?
                new ObjectParameter("tipe_periode", tipe_periode) :
                new ObjectParameter("tipe_periode", typeof(string));
    
            var dimensi1Parameter = dimensi1 != null ?
                new ObjectParameter("dimensi1", dimensi1) :
                new ObjectParameter("dimensi1", typeof(string));
    
            var dimensi2Parameter = dimensi2 != null ?
                new ObjectParameter("dimensi2", dimensi2) :
                new ObjectParameter("dimensi2", typeof(string));
    
            var periode_fromParameter = periode_from.HasValue ?
                new ObjectParameter("periode_from", periode_from) :
                new ObjectParameter("periode_from", typeof(System.DateTime));
    
            var periode_untilParameter = periode_until.HasValue ?
                new ObjectParameter("periode_until", periode_until) :
                new ObjectParameter("periode_until", typeof(System.DateTime));
    
            var level_alertParameter = level_alert != null ?
                new ObjectParameter("level_alert", level_alert) :
                new ObjectParameter("level_alert", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_getGroupedRJPOtherLJK_Result>("usp_getGroupedRJPOtherLJK", member_type_codeParameter, member_codeParameter, member_type_code2Parameter, member_code2Parameter, tipe_periodeParameter, dimensi1Parameter, dimensi2Parameter, periode_fromParameter, periode_untilParameter, level_alertParameter);
        }
    
        public virtual ObjectResult<usp_getHmlMcdfa_Result> usp_getHmlMcdfa(string tipe_dashboard, string kode_report, string jenis_ljk, string ljk, string hml, string mcdfa, string periode_awal, string periode_akhir, string dimensi1)
        {
            var tipe_dashboardParameter = tipe_dashboard != null ?
                new ObjectParameter("tipe_dashboard", tipe_dashboard) :
                new ObjectParameter("tipe_dashboard", typeof(string));
    
            var kode_reportParameter = kode_report != null ?
                new ObjectParameter("kode_report", kode_report) :
                new ObjectParameter("kode_report", typeof(string));
    
            var jenis_ljkParameter = jenis_ljk != null ?
                new ObjectParameter("jenis_ljk", jenis_ljk) :
                new ObjectParameter("jenis_ljk", typeof(string));
    
            var ljkParameter = ljk != null ?
                new ObjectParameter("ljk", ljk) :
                new ObjectParameter("ljk", typeof(string));
    
            var hmlParameter = hml != null ?
                new ObjectParameter("hml", hml) :
                new ObjectParameter("hml", typeof(string));
    
            var mcdfaParameter = mcdfa != null ?
                new ObjectParameter("mcdfa", mcdfa) :
                new ObjectParameter("mcdfa", typeof(string));
    
            var periode_awalParameter = periode_awal != null ?
                new ObjectParameter("periode_awal", periode_awal) :
                new ObjectParameter("periode_awal", typeof(string));
    
            var periode_akhirParameter = periode_akhir != null ?
                new ObjectParameter("periode_akhir", periode_akhir) :
                new ObjectParameter("periode_akhir", typeof(string));
    
            var dimensi1Parameter = dimensi1 != null ?
                new ObjectParameter("dimensi1", dimensi1) :
                new ObjectParameter("dimensi1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_getHmlMcdfa_Result>("usp_getHmlMcdfa", tipe_dashboardParameter, kode_reportParameter, jenis_ljkParameter, ljkParameter, hmlParameter, mcdfaParameter, periode_awalParameter, periode_akhirParameter, dimensi1Parameter);
        }
    
        public virtual ObjectResult<usp_getListMenu_Result> usp_getListMenu(string tipe)
        {
            var tipeParameter = tipe != null ?
                new ObjectParameter("tipe", tipe) :
                new ObjectParameter("tipe", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_getListMenu_Result>("usp_getListMenu", tipeParameter);
        }
    
        public virtual ObjectResult<usp_getListQueue_Result> usp_getListQueue()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_getListQueue_Result>("usp_getListQueue");
        }
    
        public virtual ObjectResult<string> usp_getListUserPengawasForDelete()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_getListUserPengawasForDelete");
        }
    
        public virtual ObjectResult<string> usp_getListUserSync()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_getListUserSync");
        }
    
        public virtual ObjectResult<usp_getLJKPengawas_Result> usp_getLJKPengawas(string userID)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_getLJKPengawas_Result>("usp_getLJKPengawas", userIDParameter);
        }
    
        public virtual ObjectResult<usp_getLogOutliers_Result> usp_getLogOutliers(string jenis_ljk, string ljk, string periode_awal, string periode_akhir)
        {
            var jenis_ljkParameter = jenis_ljk != null ?
                new ObjectParameter("jenis_ljk", jenis_ljk) :
                new ObjectParameter("jenis_ljk", typeof(string));
    
            var ljkParameter = ljk != null ?
                new ObjectParameter("ljk", ljk) :
                new ObjectParameter("ljk", typeof(string));
    
            var periode_awalParameter = periode_awal != null ?
                new ObjectParameter("periode_awal", periode_awal) :
                new ObjectParameter("periode_awal", typeof(string));
    
            var periode_akhirParameter = periode_akhir != null ?
                new ObjectParameter("periode_akhir", periode_akhir) :
                new ObjectParameter("periode_akhir", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_getLogOutliers_Result>("usp_getLogOutliers", jenis_ljkParameter, ljkParameter, periode_awalParameter, periode_akhirParameter);
        }
    
        public virtual int usp_getLogOutliersAvg(string jenis_ljk, string ljk, string periode_awal, string periode_akhir, string status)
        {
            var jenis_ljkParameter = jenis_ljk != null ?
                new ObjectParameter("jenis_ljk", jenis_ljk) :
                new ObjectParameter("jenis_ljk", typeof(string));
    
            var ljkParameter = ljk != null ?
                new ObjectParameter("ljk", ljk) :
                new ObjectParameter("ljk", typeof(string));
    
            var periode_awalParameter = periode_awal != null ?
                new ObjectParameter("periode_awal", periode_awal) :
                new ObjectParameter("periode_awal", typeof(string));
    
            var periode_akhirParameter = periode_akhir != null ?
                new ObjectParameter("periode_akhir", periode_akhir) :
                new ObjectParameter("periode_akhir", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_getLogOutliersAvg", jenis_ljkParameter, ljkParameter, periode_awalParameter, periode_akhirParameter, statusParameter);
        }
    
        public virtual int usp_getLogOutliersAvgKomposisi(string jenis_ljk, string ljk, string periode_awal, string periode_akhir)
        {
            var jenis_ljkParameter = jenis_ljk != null ?
                new ObjectParameter("jenis_ljk", jenis_ljk) :
                new ObjectParameter("jenis_ljk", typeof(string));
    
            var ljkParameter = ljk != null ?
                new ObjectParameter("ljk", ljk) :
                new ObjectParameter("ljk", typeof(string));
    
            var periode_awalParameter = periode_awal != null ?
                new ObjectParameter("periode_awal", periode_awal) :
                new ObjectParameter("periode_awal", typeof(string));
    
            var periode_akhirParameter = periode_akhir != null ?
                new ObjectParameter("periode_akhir", periode_akhir) :
                new ObjectParameter("periode_akhir", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_getLogOutliersAvgKomposisi", jenis_ljkParameter, ljkParameter, periode_awalParameter, periode_akhirParameter);
        }
    
        public virtual int usp_getLogOutliersDetail(string jenis_ljk, string ljk, string periode_awal, string periode_akhir, string status)
        {
            var jenis_ljkParameter = jenis_ljk != null ?
                new ObjectParameter("jenis_ljk", jenis_ljk) :
                new ObjectParameter("jenis_ljk", typeof(string));
    
            var ljkParameter = ljk != null ?
                new ObjectParameter("ljk", ljk) :
                new ObjectParameter("ljk", typeof(string));
    
            var periode_awalParameter = periode_awal != null ?
                new ObjectParameter("periode_awal", periode_awal) :
                new ObjectParameter("periode_awal", typeof(string));
    
            var periode_akhirParameter = periode_akhir != null ?
                new ObjectParameter("periode_akhir", periode_akhir) :
                new ObjectParameter("periode_akhir", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_getLogOutliersDetail", jenis_ljkParameter, ljkParameter, periode_awalParameter, periode_akhirParameter, statusParameter);
        }
    
        public virtual ObjectResult<usp_getLogPerHour_Result> usp_getLogPerHour(string jenis_ljk, string ljk, string periode)
        {
            var jenis_ljkParameter = jenis_ljk != null ?
                new ObjectParameter("jenis_ljk", jenis_ljk) :
                new ObjectParameter("jenis_ljk", typeof(string));
    
            var ljkParameter = ljk != null ?
                new ObjectParameter("ljk", ljk) :
                new ObjectParameter("ljk", typeof(string));
    
            var periodeParameter = periode != null ?
                new ObjectParameter("periode", periode) :
                new ObjectParameter("periode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_getLogPerHour_Result>("usp_getLogPerHour", jenis_ljkParameter, ljkParameter, periodeParameter);
        }
    
        public virtual int usp_getLogPerMonth(string jenis_ljk, string ljk, string periode_awal, string periode_akhir)
        {
            var jenis_ljkParameter = jenis_ljk != null ?
                new ObjectParameter("jenis_ljk", jenis_ljk) :
                new ObjectParameter("jenis_ljk", typeof(string));
    
            var ljkParameter = ljk != null ?
                new ObjectParameter("ljk", ljk) :
                new ObjectParameter("ljk", typeof(string));
    
            var periode_awalParameter = periode_awal != null ?
                new ObjectParameter("periode_awal", periode_awal) :
                new ObjectParameter("periode_awal", typeof(string));
    
            var periode_akhirParameter = periode_akhir != null ?
                new ObjectParameter("periode_akhir", periode_akhir) :
                new ObjectParameter("periode_akhir", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_getLogPerMonth", jenis_ljkParameter, ljkParameter, periode_awalParameter, periode_akhirParameter);
        }
    
        public virtual ObjectResult<usp_getMenuDb_Result> usp_getMenuDb(string user_id, string role_name)
        {
            var user_idParameter = user_id != null ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(string));
    
            var role_nameParameter = role_name != null ?
                new ObjectParameter("role_name", role_name) :
                new ObjectParameter("role_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_getMenuDb_Result>("usp_getMenuDb", user_idParameter, role_nameParameter);
        }
    
        public virtual ObjectResult<usp_getModulChildren_Result> usp_getModulChildren(Nullable<long> node_id)
        {
            var node_idParameter = node_id.HasValue ?
                new ObjectParameter("node_id", node_id) :
                new ObjectParameter("node_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_getModulChildren_Result>("usp_getModulChildren", node_idParameter);
        }
    
        public virtual ObjectResult<usp_getNotification_Result> usp_getNotification(string user_id)
        {
            var user_idParameter = user_id != null ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_getNotification_Result>("usp_getNotification", user_idParameter);
        }
    
        public virtual ObjectResult<string> usp_getPengawasDailyALert(Nullable<System.DateTime> periode, string tipePeriode)
        {
            var periodeParameter = periode.HasValue ?
                new ObjectParameter("periode", periode) :
                new ObjectParameter("periode", typeof(System.DateTime));
    
            var tipePeriodeParameter = tipePeriode != null ?
                new ObjectParameter("tipePeriode", tipePeriode) :
                new ObjectParameter("tipePeriode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_getPengawasDailyALert", periodeParameter, tipePeriodeParameter);
        }
    
        public virtual int usp_getRJPSelfVsOtherLJK(string member_type_code, string member_code, string member_type_code2, string member_code2, string tipe_periode, string dimensi1, string dimensi2, Nullable<System.DateTime> periode_from, Nullable<System.DateTime> periode_until)
        {
            var member_type_codeParameter = member_type_code != null ?
                new ObjectParameter("member_type_code", member_type_code) :
                new ObjectParameter("member_type_code", typeof(string));
    
            var member_codeParameter = member_code != null ?
                new ObjectParameter("member_code", member_code) :
                new ObjectParameter("member_code", typeof(string));
    
            var member_type_code2Parameter = member_type_code2 != null ?
                new ObjectParameter("member_type_code2", member_type_code2) :
                new ObjectParameter("member_type_code2", typeof(string));
    
            var member_code2Parameter = member_code2 != null ?
                new ObjectParameter("member_code2", member_code2) :
                new ObjectParameter("member_code2", typeof(string));
    
            var tipe_periodeParameter = tipe_periode != null ?
                new ObjectParameter("tipe_periode", tipe_periode) :
                new ObjectParameter("tipe_periode", typeof(string));
    
            var dimensi1Parameter = dimensi1 != null ?
                new ObjectParameter("dimensi1", dimensi1) :
                new ObjectParameter("dimensi1", typeof(string));
    
            var dimensi2Parameter = dimensi2 != null ?
                new ObjectParameter("dimensi2", dimensi2) :
                new ObjectParameter("dimensi2", typeof(string));
    
            var periode_fromParameter = periode_from.HasValue ?
                new ObjectParameter("periode_from", periode_from) :
                new ObjectParameter("periode_from", typeof(System.DateTime));
    
            var periode_untilParameter = periode_until.HasValue ?
                new ObjectParameter("periode_until", periode_until) :
                new ObjectParameter("periode_until", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_getRJPSelfVsOtherLJK", member_type_codeParameter, member_codeParameter, member_type_code2Parameter, member_code2Parameter, tipe_periodeParameter, dimensi1Parameter, dimensi2Parameter, periode_fromParameter, periode_untilParameter);
        }
    
        public virtual ObjectResult<string> usp_getRoleEmail(string roleCsv)
        {
            var roleCsvParameter = roleCsv != null ?
                new ObjectParameter("roleCsv", roleCsv) :
                new ObjectParameter("roleCsv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_getRoleEmail", roleCsvParameter);
        }
    
        public virtual ObjectResult<string> usp_getRoleWithSatkerEmail(string roleCsv, Nullable<long> satker_id)
        {
            var roleCsvParameter = roleCsv != null ?
                new ObjectParameter("roleCsv", roleCsv) :
                new ObjectParameter("roleCsv", typeof(string));
    
            var satker_idParameter = satker_id.HasValue ?
                new ObjectParameter("satker_id", satker_id) :
                new ObjectParameter("satker_id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("usp_getRoleWithSatkerEmail", roleCsvParameter, satker_idParameter);
        }
    
        public virtual int usp_getSummaryJenisLJK(string selectedDQ, string jenisLJK, string period)
        {
            var selectedDQParameter = selectedDQ != null ?
                new ObjectParameter("SelectedDQ", selectedDQ) :
                new ObjectParameter("SelectedDQ", typeof(string));
    
            var jenisLJKParameter = jenisLJK != null ?
                new ObjectParameter("JenisLJK", jenisLJK) :
                new ObjectParameter("JenisLJK", typeof(string));
    
            var periodParameter = period != null ?
                new ObjectParameter("Period", period) :
                new ObjectParameter("Period", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_getSummaryJenisLJK", selectedDQParameter, jenisLJKParameter, periodParameter);
        }
    
        public virtual int usp_getSummaryLJK(string jenisLJK, string kodeLJK, string period)
        {
            var jenisLJKParameter = jenisLJK != null ?
                new ObjectParameter("JenisLJK", jenisLJK) :
                new ObjectParameter("JenisLJK", typeof(string));
    
            var kodeLJKParameter = kodeLJK != null ?
                new ObjectParameter("KodeLJK", kodeLJK) :
                new ObjectParameter("KodeLJK", typeof(string));
    
            var periodParameter = period != null ?
                new ObjectParameter("Period", period) :
                new ObjectParameter("Period", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_getSummaryLJK", jenisLJKParameter, kodeLJKParameter, periodParameter);
        }
    
        public virtual ObjectResult<usp_getSummaryRowTable_Result> usp_getSummaryRowTable(Nullable<System.DateTime> period, string tipe, string jenis_ljk, string ljk)
        {
            var periodParameter = period.HasValue ?
                new ObjectParameter("period", period) :
                new ObjectParameter("period", typeof(System.DateTime));
    
            var tipeParameter = tipe != null ?
                new ObjectParameter("tipe", tipe) :
                new ObjectParameter("tipe", typeof(string));
    
            var jenis_ljkParameter = jenis_ljk != null ?
                new ObjectParameter("jenis_ljk", jenis_ljk) :
                new ObjectParameter("jenis_ljk", typeof(string));
    
            var ljkParameter = ljk != null ?
                new ObjectParameter("ljk", ljk) :
                new ObjectParameter("ljk", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_getSummaryRowTable_Result>("usp_getSummaryRowTable", periodParameter, tipeParameter, jenis_ljkParameter, ljkParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> usp_getTotalPelapor(string userID)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("usp_getTotalPelapor", userIDParameter);
        }
    
        public virtual int usp_updSBPembandingFromRJPSeflBulanan(Nullable<System.DateTime> periode_from)
        {
            var periode_fromParameter = periode_from.HasValue ?
                new ObjectParameter("periode_from", periode_from) :
                new ObjectParameter("periode_from", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_updSBPembandingFromRJPSeflBulanan", periode_fromParameter);
        }
    }
}
