//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDA.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimTime
    {
        public System.DateTime PK_Date { get; set; }
        public string Date_Name { get; set; }
        public Nullable<System.DateTime> Year { get; set; }
        public string Year_Name { get; set; }
        public Nullable<System.DateTime> Half_Year { get; set; }
        public string Half_Year_Name { get; set; }
        public Nullable<System.DateTime> Quarter { get; set; }
        public string Quarter_Name { get; set; }
        public Nullable<System.DateTime> Trimester { get; set; }
        public string Trimester_Name { get; set; }
        public Nullable<System.DateTime> Month { get; set; }
        public string Month_Name { get; set; }
        public Nullable<System.DateTime> Week { get; set; }
        public string Week_Name { get; set; }
        public Nullable<int> Day_Of_Year { get; set; }
        public string Day_Of_Year_Name { get; set; }
        public Nullable<int> Day_Of_Half_Year { get; set; }
        public string Day_Of_Half_Year_Name { get; set; }
        public Nullable<int> Day_Of_Trimester { get; set; }
        public string Day_Of_Trimester_Name { get; set; }
        public Nullable<int> Day_Of_Quarter { get; set; }
        public string Day_Of_Quarter_Name { get; set; }
        public Nullable<int> Day_Of_Month { get; set; }
        public string Day_Of_Month_Name { get; set; }
        public Nullable<int> Day_Of_Week { get; set; }
        public string Day_Of_Week_Name { get; set; }
        public Nullable<int> Week_Of_Year { get; set; }
        public string Week_Of_Year_Name { get; set; }
        public Nullable<int> Month_Of_Year { get; set; }
        public string Month_Of_Year_Name { get; set; }
        public Nullable<int> Month_Of_Half_Year { get; set; }
        public string Month_Of_Half_Year_Name { get; set; }
        public Nullable<int> Month_Of_Trimester { get; set; }
        public string Month_Of_Trimester_Name { get; set; }
        public Nullable<int> Month_Of_Quarter { get; set; }
        public string Month_Of_Quarter_Name { get; set; }
        public Nullable<int> Quarter_Of_Year { get; set; }
        public string Quarter_Of_Year_Name { get; set; }
        public Nullable<int> Quarter_Of_Half_Year { get; set; }
        public string Quarter_Of_Half_Year_Name { get; set; }
        public Nullable<int> Trimester_Of_Year { get; set; }
        public string Trimester_Of_Year_Name { get; set; }
        public Nullable<int> Half_Year_Of_Year { get; set; }
        public string Half_Year_Of_Year_Name { get; set; }
    }
}
