//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDA.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email_In
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Email_In()
        {
            this.FWAttachment = new HashSet<FWAttachment>();
        }
    
        public long emin_id { get; set; }
        public string emin_to { get; set; }
        public string emin_from { get; set; }
        public string emin_cc { get; set; }
        public string emin_reply_to { get; set; }
        public string emin_subject { get; set; }
        public string emin_body { get; set; }
        public string emin_header { get; set; }
        public Nullable<System.DateTime> emin_date { get; set; }
        public Nullable<System.DateTime> emin_receive_date { get; set; }
        public Nullable<bool> emin_is_bounce { get; set; }
        public bool emin_is_read { get; set; }
        public string emin_message_id { get; set; }
        public string emin_bounce_message_id { get; set; }
        public string emin_bounce_from { get; set; }
        public string emin_bounce_subject { get; set; }
        public Nullable<long> emin_unique_id { get; set; }
        public string emin_server { get; set; }
        public Nullable<int> emin_attach_file_count { get; set; }
        public Nullable<bool> emin_is_spam { get; set; }
        public string stsrc { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FWAttachment> FWAttachment { get; set; }
    }
}
