//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDA.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FWCalendar
    {
        public string CalendarId { get; set; }
        public System.DateTime CalendarDate { get; set; }
        public string CalendarDayName { get; set; }
        public string CalendarMonthName { get; set; }
        public short CalendarYear { get; set; }
        public byte CalendarDay { get; set; }
        public byte CalendarMonth { get; set; }
        public byte CalendarQuarter { get; set; }
        public bool CalendarHoliday { get; set; }
        public string CalendarHolidayKeterangan { get; set; }
        public string CalendarType { get; set; }
    }
}
