//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDA.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FWEmailQueue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FWEmailQueue()
        {
            this.FWNoticeQueues = new HashSet<FWNoticeQueue>();
        }
    
        public long EmailqId { get; set; }
        public string EmailqTo { get; set; }
        public string EmailqFrom { get; set; }
        public string EmailqCc { get; set; }
        public string EmailqBcc { get; set; }
        public string EmailqReplyTo { get; set; }
        public string EmailqSubject { get; set; }
        public string EmailqBody { get; set; }
        public string EmailqAttchName1 { get; set; }
        public byte[] EmailqAttchFile1 { get; set; }
        public string EmailqAttchName2 { get; set; }
        public byte[] EmailqAttchFile2 { get; set; }
        public string EmailqAttchName3 { get; set; }
        public byte[] EmailqAttchFile3 { get; set; }
        public Nullable<byte> EmailqStatus { get; set; }
        public System.DateTime EmailqQueueDate { get; set; }
        public System.DateTime EmailqScheduledSent { get; set; }
        public Nullable<System.DateTime> EmailqSentDate { get; set; }
        public Nullable<int> EmailqSentTry { get; set; }
        public string EmailqProcess { get; set; }
        public Nullable<long> EmailqProcessId { get; set; }
        public string EmailqErrorText { get; set; }
        public string Stsrc { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDatetime { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDatetime { get; set; }
        public Nullable<long> NoticeId { get; set; }
        public string EmailqMessageId { get; set; }
    
        public virtual FWNotice FWNotice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FWNoticeQueue> FWNoticeQueues { get; set; }
    }
}
