//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDA.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FWKodeDetail
    {
        public long KodId { get; set; }
        public string KofId { get; set; }
        public string KodTipe { get; set; }
        public int KodUrut { get; set; }
        public Nullable<byte> KodLength { get; set; }
        public string KodCatatan { get; set; }
        public string KodChar { get; set; }
        public string KodParamKode { get; set; }
        public bool KodParamAsCounter { get; set; }
    
        public virtual FWKodeFormat FWKodeFormat { get; set; }
    }
}
