//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDA.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FWNoticeQueue
    {
        public long NotqId { get; set; }
        public string NottId { get; set; }
        public System.DateTime NottDate { get; set; }
        public string NotqTitle { get; set; }
        public Nullable<System.DateTime> NottSentDate { get; set; }
        public string NotqUser { get; set; }
        public string NotqContent { get; set; }
        public byte NotqStatus { get; set; }
        public Nullable<long> EmailqId { get; set; }
        public string NotqEmail { get; set; }
        public string Stsrc { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDatetime { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDatetime { get; set; }
    
        public virtual FWEmailQueue FWEmailQueue { get; set; }
        public virtual FWNoticeTemplate FWNoticeTemplate { get; set; }
        public virtual UserMaster UserMaster { get; set; }
    }
}
