//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDA.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FWNotice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FWNotice()
        {
            this.FWEmailQueues = new HashSet<FWEmailQueue>();
        }
    
        public long NoticeId { get; set; }
        public string NoticeTitle { get; set; }
        public string NoticeSender { get; set; }
        public string NoticeTo { get; set; }
        public string NoticeCc { get; set; }
        public string NoticeBcc { get; set; }
        public bool NoticeBatchStatus { get; set; }
        public string NoticeContent { get; set; }
        public string NoticeSmallContent { get; set; }
        public string NottId { get; set; }
        public string Stsrc { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDatetime { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDatetime { get; set; }
        public string NoticeRefId { get; set; }
        public string NoticeRefId2 { get; set; }
        public string NoticeRefId3 { get; set; }
        public string NoticeBatchUsers { get; set; }
        public Nullable<long> ApprId { get; set; }
        public string NoticeCatatan { get; set; }
        public string NoticeAttachLink { get; set; }
        public string NoticeAttachLink2 { get; set; }
        public string NoticeAttachLink3 { get; set; }
        public string NoticeRdefParamCsv { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FWEmailQueue> FWEmailQueues { get; set; }
        public virtual FWNoticeTemplate FWNoticeTemplate { get; set; }
    }
}
