//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDA.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FWRefModulMenu
    {
        public long ModMenuId { get; set; }
        public Nullable<long> ModId { get; set; }
        public string ModMenuNama { get; set; }
        public string ModMenuAksi { get; set; }
        public string ModMenuUrl { get; set; }
        public Nullable<bool> ModMenuIsHidden { get; set; }
        public string Stsrc { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDatetime { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDatetime { get; set; }
    
        public virtual FWRefModul FWRefModul { get; set; }
    }
}
