//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDA.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FWUserLostPassword
    {
        public long UlpId { get; set; }
        public System.DateTime UlpDate { get; set; }
        public string UserId { get; set; }
        public System.DateTime UlpExpireDate { get; set; }
        public string UlpEmail { get; set; }
        public string UlpCode { get; set; }
        public string UlpStatus { get; set; }
        public Nullable<System.DateTime> UlpResetDate { get; set; }
        public string Stsrc { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDatetime { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDatetime { get; set; }
    
        public virtual UserMaster UserMaster { get; set; }
    }
}
