//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDA.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FWWorkday
    {
        public long WorkdayId { get; set; }
        public short WorkdayYear { get; set; }
        public string WorkdayDayName { get; set; }
        public Nullable<System.DateTime> WorkdayStart { get; set; }
        public Nullable<System.DateTime> WorkdayEnd { get; set; }
        public string Stsrc { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDatetime { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDatetime { get; set; }
        public Nullable<byte> WorkdayDay { get; set; }
        public string CalendarType { get; set; }
    }
}
