//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDA.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Help
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Help()
        {
            this.FWAttachment = new HashSet<FWAttachment>();
        }
    
        public long help_id { get; set; }
        public int help_urut { get; set; }
        public string help_nama { get; set; }
        public string help_catatan { get; set; }
        public Nullable<System.DateTime> help_last_update { get; set; }
        public string help_last_update_by { get; set; }
        public string stsrc { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FWAttachment> FWAttachment { get; set; }
    }
}
