//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDA.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ip_ownership
    {
        public System.DateTime dm_periode { get; set; }
        public long rowid { get; set; }
        public string sid { get; set; }
        public string nama_sid { get; set; }
        public string trade_id { get; set; }
        public string ktp { get; set; }
        public string npwp { get; set; }
        public string securitycode { get; set; }
        public string securityname { get; set; }
        public string rekening_status { get; set; }
        public string accountbalancestatuscode { get; set; }
        public Nullable<long> volume { get; set; }
        public Nullable<decimal> value { get; set; }
        public string sistem { get; set; }
        public string periode { get; set; }
    }
}
