//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDA.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class market_driven_stp_balance
    {
        public System.DateTime dm_periode { get; set; }
        public long rowid { get; set; }
        public Nullable<System.DateTime> tanggal_balance { get; set; }
        public string sid { get; set; }
        public string trading_id { get; set; }
        public string efek { get; set; }
        public string subrekening_efek { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<long> price { get; set; }
        public Nullable<System.DateTime> periode { get; set; }
    }
}
