//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDA.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class market_driven_stp_settlement_new1
    {
        public System.DateTime dm_periode { get; set; }
        public long rowid { get; set; }
        public Nullable<System.DateTime> tradingdatesk { get; set; }
        public Nullable<System.DateTime> settlementtransactiondatesk { get; set; }
        public string fpinvestorid { get; set; }
        public string tradingid { get; set; }
        public string fpsettlementaccountcode { get; set; }
        public string securitycode { get; set; }
        public string cpsettlementaccountcode { get; set; }
        public string settlementinstructiontypecode { get; set; }
        public string cpinvestorid { get; set; }
        public Nullable<long> settlementquantity { get; set; }
        public Nullable<long> settlementexposureamount { get; set; }
        public Nullable<System.DateTime> periode { get; set; }
    }
}
