//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDA.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class market_driven_rg_ng
    {
        public System.DateTime dm_periode { get; set; }
        public long rowid { get; set; }
        public string history_type { get; set; }
        public Nullable<System.DateTime> periode_lvl1 { get; set; }
        public Nullable<System.DateTime> periode_lvl2 { get; set; }
        public Nullable<System.DateTime> periode_lvl3 { get; set; }
        public string security_code { get; set; }
        public string market { get; set; }
        public Nullable<long> volume { get; set; }
        public Nullable<decimal> value { get; set; }
        public Nullable<int> freq { get; set; }
        public Nullable<int> low { get; set; }
        public Nullable<int> high { get; set; }
        public Nullable<int> close { get; set; }
        public Nullable<System.DateTime> periode { get; set; }
    }
}
