//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDA.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class master_office_ljk
    {
        public string kode_jenis_ljk { get; set; }
        public string kode_ljk { get; set; }
        public string kode_kantor_cabang { get; set; }
        public string kantor_cabang { get; set; }
        public string parent_ljk { get; set; }
        public string parent_jenis_ljk { get; set; }
        public string parent_kantor_cabang { get; set; }
        public string status_aktif { get; set; }
        public string status_delete { get; set; }
        public string create_date { get; set; }
        public string update_date { get; set; }
        public string p_date { get; set; }
        public Nullable<System.DateTime> sync_date { get; set; }
    }
}
