//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDA.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterKota
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MasterKota()
        {
            this.MasterSatkers = new HashSet<MasterSatker>();
        }
    
        public long RefKotaId { get; set; }
        public string RefKotaNama { get; set; }
        public string RefKotaDomisili { get; set; }
        public string Stsrc { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDatetime { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDatetime { get; set; }
        public Nullable<long> RefPropinsiId { get; set; }
        public string JtiCityid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterSatker> MasterSatkers { get; set; }
        public virtual MasterPropinsi MasterPropinsi { get; set; }
    }
}
