//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDA.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_Agunan
    {
        public string jenis_agunan { get; set; }
        public string nama_agunan { get; set; }
        public Nullable<System.DateTime> sync_date { get; set; }
    }
}
