//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDA.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class master_user_ideb
    {
        public string user_id { get; set; }
        public string user_login_id { get; set; }
        public string user_name { get; set; }
        public string phone_number { get; set; }
        public string user_type_flag { get; set; }
        public string member_type_code { get; set; }
        public string member_code { get; set; }
        public string office_code { get; set; }
        public string employee_id { get; set; }
        public string password_latest_changed_date { get; set; }
        public string password_lock_count { get; set; }
        public string user_latest_login_date { get; set; }
        public string active_flag { get; set; }
        public string created_by { get; set; }
        public string created_datetime { get; set; }
        public string updated_by { get; set; }
        public string updated_datetime { get; set; }
        public string user_status_flag { get; set; }
        public string p_date { get; set; }
        public Nullable<System.DateTime> sync_date { get; set; }
    }
}
