//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDA.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterSatker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MasterSatker()
        {
            this.UserMasters = new HashSet<UserMaster>();
        }
    
        public long SatkerId { get; set; }
        public string SatkerKode { get; set; }
        public string SatkerNama { get; set; }
        public string SatkerTipe { get; set; }
        public Nullable<long> SatkerParentId { get; set; }
        public Nullable<long> RefKotaId { get; set; }
        public Nullable<bool> SatkerIsAudit { get; set; }
        public Nullable<short> SatkerLevel { get; set; }
        public string Stsrc { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDatetime { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDatetime { get; set; }
        public string CamOrganizationCode { get; set; }
        public string CamOrganizationParentCode { get; set; }
        public string CamOrganizationLetterCode { get; set; }
    
        public virtual MasterKota MasterKota { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserMaster> UserMasters { get; set; }
    }
}
