//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDA.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEMBER_TYPES
    {
        public string Kode_Jenis_LJK { get; set; }
        public string Deskripsi_Jenis_LJK { get; set; }
        public string Status_Aktif { get; set; }
        public string Status_Delete { get; set; }
        public string Create_Date { get; set; }
        public string Update_Date { get; set; }
    }
}
