//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDA.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ml_log_aktivitas
    {
        public System.DateTime dm_periode { get; set; }
        public long rowid { get; set; }
        public string ip_address { get; set; }
        public string nip { get; set; }
        public string user_id { get; set; }
        public string satuan_kerja { get; set; }
        public string kegiatan { get; set; }
        public string menu { get; set; }
        public string url { get; set; }
        public string input_params { get; set; }
        public string output_params { get; set; }
        public string keterangan { get; set; }
        public Nullable<System.DateTime> tanggal { get; set; }
    }
}
