//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDA.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ml_master_log
    {
        public System.DateTime dm_periode { get; set; }
        public long rowid { get; set; }
        public string kode_job { get; set; }
        public string nama_job { get; set; }
        public string nama_sequence { get; set; }
        public string tabel_target { get; set; }
        public string tabel_sumber { get; set; }
        public string lokasi_script { get; set; }
        public Nullable<int> urutan_proses { get; set; }
        public Nullable<System.DateTime> waktu_scheduler { get; set; }
    }
}
