//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDA.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class osida_pembanding_populasi_chart
    {
        public System.DateTime dm_periode { get; set; }
        public long rowid { get; set; }
        public string dm_jenis_ljk { get; set; }
        public string dm_kode_ljk { get; set; }
        public Nullable<decimal> dm_plafon_takeover_231_hari_terakhir { get; set; }
        public Nullable<int> dm_jumlah_rekening_takeover_231_hari_terakhir { get; set; }
        public Nullable<decimal> dm_plafon_1_tahun_terakhir { get; set; }
        public Nullable<int> dm_jumlah_rekening_1_tahun_terakhir { get; set; }
        public Nullable<decimal> dm_plafon_231_hari_terakhir { get; set; }
        public Nullable<int> dm_jumlah_rekening_231_hari_terakhir { get; set; }
    }
}
