//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDA.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class osida_nik_tidak_konsisten_mst
    {
        public System.DateTime dm_periode { get; set; }
        public long rowid { get; set; }
        public string dm_jenis_ljk { get; set; }
        public string dm_kode_ljk { get; set; }
        public string dm_kode_kantor_cabang { get; set; }
        public string dm_nama_ljk { get; set; }
        public string dm_nama_kantor_cabang { get; set; }
        public string dm_cif { get; set; }
        public string dm_nama_nasabah { get; set; }
        public string dm_jenis_kelamin { get; set; }
        public Nullable<System.DateTime> dm_tgl_lahir { get; set; }
        public string dm_no_identitas { get; set; }
        public string dm_jumlah_rekening { get; set; }
        public Nullable<decimal> dm_total_plafon_aktif { get; set; }
        public Nullable<decimal> dm_total_baki_debet { get; set; }
        public Nullable<decimal> dm_kualitas_terburuk { get; set; }
        public Nullable<decimal> dm_tunggakan_pokok { get; set; }
        public Nullable<decimal> dm_tunggakan_bunga { get; set; }
    }
}
