//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDA.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class pasarmodal_market_driven_rg_ng
    {
        public string history_type { get; set; }
        public string periode_lvl1 { get; set; }
        public string periode_lvl2 { get; set; }
        public string periode_lvl3 { get; set; }
        public string security_code { get; set; }
        public string market { get; set; }
        public long volume { get; set; }
        public double value { get; set; }
        public int freq { get; set; }
        public short low { get; set; }
        public short high { get; set; }
        public short close { get; set; }
        public string periode { get; set; }
    }
}
