//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDA.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class pe_segmentation_det_reverse_repo_new
    {
        public System.DateTime calendardate { get; set; }
        public Nullable<int> securitycompanysk { get; set; }
        public string securitycompanycode { get; set; }
        public string securitycompanyname { get; set; }
        public string securitycode { get; set; }
        public string sellername { get; set; }
        public System.DateTime buyingdate { get; set; }
        public System.DateTime sellingdate { get; set; }
        public Nullable<double> buyingamount { get; set; }
        public Nullable<double> sellingamount { get; set; }
        public string collateralsecuritycode { get; set; }
        public Nullable<double> collateralamount { get; set; }
        public Nullable<double> fairmarketvalue { get; set; }
        public Nullable<double> liabilitiesrankingvalue { get; set; }
        public string periode { get; set; }
    }
}
