//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDA.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class pe_segmentation_bridging_detail
    {
        public System.DateTime calendardate { get; set; }
        public Nullable<int> securitycompanysk { get; set; }
        public string securitycompanycode { get; set; }
        public string securitycompanyname { get; set; }
        public string f_level_1 { get; set; }
        public string f_level_2 { get; set; }
        public Nullable<double> total_balance { get; set; }
        public Nullable<double> total_aset_lancar { get; set; }
        public string persentase { get; set; }
        public Nullable<double> fairmarketvalue { get; set; }
        public Nullable<int> flag { get; set; }
        public string periode { get; set; }
    }
}
