//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDA.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class pe_segmentation_geo
    {
        public System.DateTime dm_periode { get; set; }
        public long rowid { get; set; }
        public Nullable<System.DateTime> calendardate { get; set; }
        public Nullable<int> securitycompanysk { get; set; }
        public string securitycompanycode { get; set; }
        public string securitycompanyname { get; set; }
        public Nullable<int> periode { get; set; }
        public string pe { get; set; }
        public string market { get; set; }
        public string investor_type { get; set; }
        public string investor_origin { get; set; }
        public string country { get; set; }
        public string provinsi { get; set; }
        public string city { get; set; }
        public string dimension { get; set; }
        public Nullable<decimal> current_value { get; set; }
        public string growth_type { get; set; }
        public Nullable<decimal> prev_value { get; set; }
        public string prev_period { get; set; }
        public string pperiode { get; set; }
    }
}
