//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDA.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class pe_segmentation_summary_transaction_sid
    {
        public System.DateTime dm_periode { get; set; }
        public long rowid { get; set; }
        public Nullable<System.DateTime> basedate { get; set; }
        public string pe { get; set; }
        public string sid { get; set; }
        public string tradeid { get; set; }
        public string sre { get; set; }
        public string securitycode { get; set; }
        public string securityphysicaltypecode { get; set; }
        public Nullable<int> portfolioquantity { get; set; }
        public Nullable<int> portfolioamount { get; set; }
        public Nullable<int> accountbalancestatuscode { get; set; }
        public string settlementaccountownertypecode { get; set; }
        public Nullable<int> settlementaccounttypecode { get; set; }
        public Nullable<System.DateTime> yearmonth { get; set; }
        public Nullable<System.DateTime> pyer_month { get; set; }
        public Nullable<System.DateTime> pperiode { get; set; }
        public Nullable<int> prange { get; set; }
        public string exchangemembercode { get; set; }
        public string nama_sid { get; set; }
        public string full_name { get; set; }
        public string sre001 { get; set; }
        public string sre_status { get; set; }
        public string investor_type { get; set; }
        public string investor_origin { get; set; }
        public string country { get; set; }
        public string provinsi { get; set; }
        public string kota { get; set; }
        public string jenis_kelamin { get; set; }
        public string golonganusia { get; set; }
        public string pendidikan { get; set; }
        public string pekerjaan { get; set; }
        public string pinghasilan_individu { get; set; }
        public string pengahasilan_institusi { get; set; }
        public Nullable<System.DateTime> createddate { get; set; }
        public string new_sre { get; set; }
        public string market { get; set; }
        public Nullable<System.DateTime> investorlasttransactiondate { get; set; }
        public Nullable<int> investorlasttransactionindays { get; set; }
        public Nullable<int> maxpelasttransactionindays { get; set; }
        public Nullable<int> investorrecencyscore { get; set; }
        public Nullable<int> investortransactionfreq { get; set; }
        public Nullable<int> investortotalvalue { get; set; }
        public Nullable<int> maxinvestorfreq { get; set; }
        public Nullable<int> maxnvestorvalueinpe { get; set; }
        public string q1_r { get; set; }
        public string q3_r { get; set; }
        public string q1_f { get; set; }
        public string q3_f { get; set; }
        public string q1_m { get; set; }
        public string q3_m { get; set; }
        public string r { get; set; }
        public string f { get; set; }
        public string m { get; set; }
        public string basis_investor { get; set; }
        public string basis_investor_1_ { get; set; }
        public Nullable<int> inputrange { get; set; }
        public Nullable<System.DateTime> pyearmonth { get; set; }
    }
}
