//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDA.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class pe_segmentation_det_jaminan_margin_sum
    {
        public long rowid { get; set; }
        public System.DateTime calendardate { get; set; }
        public Nullable<int> securitycompanysk { get; set; }
        public string securitycompanycode { get; set; }
        public string securitycompanyname { get; set; }
        public Nullable<int> mkbdvd510accountsk { get; set; }
        public string mkbdvd510accountcode { get; set; }
        public string mkbdvd510description { get; set; }
        public Nullable<long> fairmarketvalue { get; set; }
        public System.DateTime periode { get; set; }
    }
}
