//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDA.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class pe_segmentation_pendanaan_per_mkbd
    {
        public System.DateTime dm_periode { get; set; }
        public long rowid { get; set; }
        public Nullable<System.DateTime> calendardate { get; set; }
        public Nullable<int> securitycompanysk { get; set; }
        public string securitycompanycode { get; set; }
        public string securitycompanyname { get; set; }
        public Nullable<int> mkbdaccountsk { get; set; }
        public string mkbdaccountcode { get; set; }
        public string mkbdaccountname { get; set; }
        public Nullable<decimal> mkbdaccountbalance { get; set; }
        public Nullable<int> mkbdaccountsk_mkbd { get; set; }
        public string mkbdaccountcode_mkbd { get; set; }
        public string mkbdaccountname_mkbd { get; set; }
        public Nullable<decimal> mkbdaccountbalance_mkbd { get; set; }
        public Nullable<int> sort_no { get; set; }
        public string periode { get; set; }
    }
}
