//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDA.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PM_dimSecurityCompanies
    {
        public decimal SecurityCompanySK { get; set; }
        public string SecurityCompanyCode { get; set; }
        public string SecurityCompanyName { get; set; }
        public string SPABNo { get; set; }
        public Nullable<System.DateTime> SPABDate { get; set; }
        public string LicenseNo { get; set; }
        public string ShareNo { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string InternalCode { get; set; }
        public string ReinfoCode { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
        public string CurrentStatus { get; set; }
        public Nullable<decimal> CapitalSourceTypeSK { get; set; }
        public string CapitalSourceTypeCode { get; set; }
        public Nullable<decimal> EffectiveStartDateSK { get; set; }
        public Nullable<System.DateTime> EffectiveStartDate { get; set; }
        public Nullable<decimal> EffectiveEndDateSK { get; set; }
        public Nullable<System.DateTime> EffectiveEndDate { get; set; }
        public Nullable<decimal> EMOperationalStatusSK { get; set; }
        public string EMOperationalStatusCode { get; set; }
        public Nullable<decimal> BaseCapital { get; set; }
        public Nullable<decimal> DepositsCapital { get; set; }
        public string RegisterNumber { get; set; }
        public string CompanyLogoImageURL { get; set; }
        public string PPEFlag { get; set; }
        public string PEEFlag { get; set; }
        public string MIFlag { get; set; }
        public Nullable<decimal> LicenseTypeCombinationSK { get; set; }
        public string LicenseTypeCombinationCode { get; set; }
        public string RemoteFlag { get; set; }
        public string DMAFlag { get; set; }
        public string OnlineFlag { get; set; }
        public string AlgoritmicFlag { get; set; }
        public Nullable<decimal> TransactionMethodCombinationSK { get; set; }
        public string TransactionMethodCombinationCode { get; set; }
        public Nullable<decimal> EMMarginTypeSK { get; set; }
        public string EMMarginTypeCode { get; set; }
        public Nullable<decimal> SecurityCompanyTypeSK { get; set; }
        public string SecurityCompanyTypeCode { get; set; }
        public string ABFlag { get; set; }
        public Nullable<decimal> DataSourceSK { get; set; }
        public string DataSourceCode { get; set; }
    }
}
