//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDA.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RptGrid_Queue
    {
        public long rgq_id { get; set; }
        public Nullable<long> rg_id { get; set; }
        public string rgq_query { get; set; }
        public string rgq_params { get; set; }
        public string rgq_nama { get; set; }
        public string rgq_requestor { get; set; }
        public System.DateTime rgq_date { get; set; }
        public Nullable<System.DateTime> rgq_start { get; set; }
        public Nullable<System.DateTime> rgq_end { get; set; }
        public string rgq_status { get; set; }
        public byte rgq_priority { get; set; }
        public int rgq_urut { get; set; }
        public string rgq_error_message { get; set; }
        public Nullable<int> rgq_result_filesize { get; set; }
        public string rgq_result_filename { get; set; }
        public Nullable<int> rgq_result_rowcount { get; set; }
        public string stsrc { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public string rgq_tablename { get; set; }
    
        public virtual RptGrid RptGrid { get; set; }
    }
}
