//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDA.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thread_Post
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Thread_Post()
        {
            this.FWAttachments = new HashSet<FWAttachment>();
        }
    
        public long post_id { get; set; }
        public long thread_id { get; set; }
        public string post_user { get; set; }
        public string post_title { get; set; }
        public string post_content { get; set; }
        public System.DateTime post_date { get; set; }
        public Nullable<System.DateTime> post_last_edit_date { get; set; }
        public string post_last_edit_by { get; set; }
        public int post_urut { get; set; }
        public bool post_pujk_view { get; set; }
        public bool post_konsumen_view { get; set; }
        public string post_last_edit_reason { get; set; }
        public Nullable<long> kb_id { get; set; }
        public Nullable<int> kb_rate { get; set; }
        public string stsrc { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FWAttachment> FWAttachments { get; set; }
        public virtual Thread Thread { get; set; }
        public virtual UserMaster UserMaster { get; set; }
    }
}
