//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDA.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thread
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Thread()
        {
            this.Thread_Post = new HashSet<Thread_Post>();
        }
    
        public long thread_id { get; set; }
        public string thread_title { get; set; }
        public string thread_content { get; set; }
        public string thread_owner { get; set; }
        public System.DateTime thread_start_date { get; set; }
        public System.DateTime thread_last_post { get; set; }
        public string thread_last_replier { get; set; }
        public string stsrc { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public string modified_by { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Thread_Post> Thread_Post { get; set; }
        public virtual UserMaster UserMaster { get; set; }
    }
}
