//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDA.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserMaster()
        {
            this.FWNoticeQueues = new HashSet<FWNoticeQueue>();
            this.FWUserLostPasswords = new HashSet<FWUserLostPassword>();
            this.FWUserRoles = new HashSet<FWUserRole>();
            this.KonfigurasiALertDetails = new HashSet<KonfigurasiALertDetail>();
            this.Threads = new HashSet<Thread>();
            this.Thread_Post = new HashSet<Thread_Post>();
        }
    
        public string UserId { get; set; }
        public string UserKode { get; set; }
        public string UserLdap { get; set; }
        public string UserNama { get; set; }
        public string UserAlamat { get; set; }
        public string UserTelp { get; set; }
        public string UserPassword { get; set; }
        public Nullable<System.DateTime> UserLastLogin { get; set; }
        public string UserEmail { get; set; }
        public string UserMainRole { get; set; }
        public string UserDivisi { get; set; }
        public Nullable<System.DateTime> UserPasswordLastchange { get; set; }
        public int UserFailedLoginCount { get; set; }
        public Nullable<System.DateTime> UserBlockedDate { get; set; }
        public string UserStatus { get; set; }
        public string UserLdapDepartment { get; set; }
        public string UserLdapOffice { get; set; }
        public string UserLdapDescription { get; set; }
        public string UserRolesCsv { get; set; }
        public string Stsrc { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDatetime { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDatetime { get; set; }
        public Nullable<long> CamUserId { get; set; }
        public Nullable<long> SatkerId { get; set; }
        public string IpAddress { get; set; }
        public Nullable<System.DateTime> UserNoticeLastRead { get; set; }
        public string UserAgent { get; set; }
        public Nullable<System.DateTime> LastTimeCookies { get; set; }
        public Nullable<bool> user_is_notifredalert { get; set; }
        public Nullable<bool> user_is_notifyellowalert { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FWNoticeQueue> FWNoticeQueues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FWUserLostPassword> FWUserLostPasswords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FWUserRole> FWUserRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KonfigurasiALertDetail> KonfigurasiALertDetails { get; set; }
        public virtual MasterSatker MasterSatker { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Thread> Threads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Thread_Post> Thread_Post { get; set; }
    }
}
