//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDA.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Modul
    {
        public int ID { get; set; }
        public Nullable<long> ModId { get; set; }
        public Nullable<long> ParentModId { get; set; }
        public Nullable<long> ModMenuId { get; set; }
        public string ModKodeTeks { get; set; }
        public string ModKode { get; set; }
        public string ModNama { get; set; }
        public long ModUrut { get; set; }
        public string ModKey { get; set; }
        public string ModMenuUrl { get; set; }
        public string ModMenuAksi { get; set; }
        public string Stsrc { get; set; }
        public string ModIsPublic { get; set; }
        public string ModMenuIsHidden { get; set; }
    }
}
