//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDA.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_TableDictionary
    {
        public string DBName { get; set; }
        public string TableName { get; set; }
        public string SchemaName { get; set; }
        public string ColumnName { get; set; }
        public string DataType { get; set; }
        public Nullable<bool> AllowNull { get; set; }
        public string DefaultText { get; set; }
        public Nullable<int> Length { get; set; }
        public byte NumericPrecision { get; set; }
        public byte NumericScale { get; set; }
        public int ColumnId { get; set; }
    }
}
