namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class agunan_id_anomali
{
    public System.DateTime dm_periode { get; set; }
    public long rowid { get; set; }
    public string dm_jenis_ljk { get; set; }
    public string dm_kode_ljk { get; set; }
    public string dm_cif { get; set; }
    public string dm_nama_debitur { get; set; }
    public string dm_no_agunan { get; set; }
    public string dm_jenis_agunan { get; set; }
    public string dm_dokumen_kepemilikan_agunan { get; set; }
    public string dm_lokasi_agunan { get; set; }
    public string dm_status_paripasu { get; set; }
    public Nullable<double> dm_persen_paripasu { get; set; }
    public Nullable<double> dm_similarity_score { get; set; }
    public Nullable<int> dm_similarity_result { get; set; }
}

}