namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Alert_Master
{
    public string KODE_ALERT { get; set; }
    public string NAMA_ALERT { get; set; }
    public string TIPE_PERIODE_CSV { get; set; }
    public string DIMENSI1_NAME { get; set; }
    public string DIMENSI2_NAME { get; set; }
    public string DIMENSI3_NAME { get; set; }
    public string DIMENSI4_NAME { get; set; }
    public string DIMENSI5_NAME { get; set; }
    public string stsrc { get; set; }
    public string created_by { get; set; }
    public Nullable<System.DateTime> date_created { get; set; }
    public string modified_by { get; set; }
    public Nullable<System.DateTime> date_modified { get; set; }
}

}