namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class AuditTrail
{
    public long AuditId { get; set; }
    public string AuditTipe { get; set; }
    public string AuditCause { get; set; }
    public System.DateTime AuditDate { get; set; }
    public string AuditIpAddress { get; set; }
    public string AuditUser { get; set; }
    public string AuditDebtorName { get; set; }
    public string AuditPrevUrl { get; set; }
    public string AuditUrl { get; set; }
    public string AuditObjType { get; set; }
    public string AuditObjId { get; set; }
    public string AuditObjCode { get; set; }
    public string AuditXml { get; set; }
    public string AuditJson { get; set; }
    public string AuditErrMsg { get; set; }
    public string AuditMenu { get; set; }
}

}