namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class BDA2_Table_Period
{
    public string TableName { get; set; }
    public System.DateTime Period { get; set; }
    public Nullable<int> Rows { get; set; }
    public Nullable<System.DateTime> LastProcess { get; set; }
}

}