namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class BDA_Log_PerHour
{
    public long rowid { get; set; }
    public string member_type_code { get; set; }
    public string member_code { get; set; }
    public Nullable<System.DateTime> periode { get; set; }
    public Nullable<int> hour { get; set; }
    public Nullable<long> cnt_user_id { get; set; }
    public Nullable<long> cnt_act { get; set; }
}

}