namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class BDA_HML_MCDFA
{
    public long rowid { get; set; }
    public string kode_report { get; set; }
    public string dimensi1 { get; set; }
    public System.DateTime periode { get; set; }
    public string member_type_code { get; set; }
    public string member_code { get; set; }
    public string mcdfa { get; set; }
    public string hml_pareto { get; set; }
    public string mcdfa_bytaxid { get; set; }
    public string hml_pareto_bytaxid { get; set; }
    public Nullable<decimal> sum_credit_limit { get; set; }
    public Nullable<decimal> sum_outstanding { get; set; }
    public Nullable<long> sum_qty_distinct { get; set; }
    public Nullable<long> sum_qty_account { get; set; }
}

}