namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class BDA_LogOutliers_Act
{
    public long rowid { get; set; }
    public string member_type_code { get; set; }
    public string member_code { get; set; }
    public System.DateTime periode { get; set; }
    public string status_count_activity { get; set; }
    public string user_id { get; set; }
    public Nullable<long> act_count { get; set; }
    public Nullable<double> above_threshold { get; set; }
    public Nullable<double> below_threshold { get; set; }
}

}