namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class coverage_map_ljkxcity
{
    public System.DateTime dm_periode { get; set; }
    public long rowid { get; set; }
    public string dm_jenis_ljk { get; set; }
    public string dm_kode_ljk { get; set; }
    public string dm_dati1 { get; set; }
    public string dm_dati2 { get; set; }
    public string dm_cakupan { get; set; }
    public Nullable<decimal> dm_nilai { get; set; }
    public string dm_kode_kota { get; set; }
}

}