namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class da_anomali_nomor_akta_badan_usaha
{
    public long rowid { get; set; }
    public System.DateTime dm_bulan_data { get; set; }
    public string dm_jenis_ljk { get; set; }
    public string dm_kode_ljk { get; set; }
    public string dm_nama_ljk { get; set; }
    public string dm_kode_kantor_cabang { get; set; }
    public string dm_nama_kantor_cabang { get; set; }
    public string dm_no_identitas_badan_usaha { get; set; }
    public string dm_nama_badan_usaha { get; set; }
    public string dm_kode_jenis_badan_usaha { get; set; }
    public string dm_tempat_pendirian { get; set; }
    public string dm_no_akta_pendirian { get; set; }
    public Nullable<System.DateTime> dm_tanggal_akta_pendirian { get; set; }
    public string dm_no_akta_perubahan_terakhir { get; set; }
    public Nullable<System.DateTime> dm_tanggal_akta_perubahan_terakhir { get; set; }
    public string dm_kode_anomali { get; set; }
}

}