namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class da_anomali_baki_debet_tidak_wajar
{
    public long rowid { get; set; }
    public System.DateTime dm_bulan_data { get; set; }
    public string dm_jenis_ljk { get; set; }
    public string dm_kode_ljk { get; set; }
    public string dm_nama_ljk { get; set; }
    public string dm_kode_kantor_cabang { get; set; }
    public string dm_nama_kantor_cabang { get; set; }
    public Nullable<decimal> dm_baki_debet { get; set; }
    public Nullable<decimal> dm_baki_debet_m1 { get; set; }
    public Nullable<decimal> dm_selisih_baki_debet_m1 { get; set; }
    public Nullable<decimal> dm__selisih_baki_debet_m1 { get; set; }
    public Nullable<decimal> dm_baki_debet_m3 { get; set; }
    public Nullable<decimal> dm_selisih_baki_debet_m3 { get; set; }
    public Nullable<decimal> dm__selisih_baki_debet_m3 { get; set; }
    public Nullable<decimal> dm_baki_debet_m6 { get; set; }
    public Nullable<decimal> dm_selisih_baki_debet_m6 { get; set; }
    public Nullable<decimal> dm__selisih_baki_debet_m6 { get; set; }
    public Nullable<decimal> dm_baki_debet_m12 { get; set; }
    public Nullable<decimal> dm_selisih_baki_debet_m12 { get; set; }
    public Nullable<decimal> dm__selisih_baki_debet_m12 { get; set; }
    public string dm_segmen { get; set; }
    public string dm_kode_anomali { get; set; }
}

}