namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class da_anomali_tingkat_suku_bunga
{
    public long rowid { get; set; }
    public System.DateTime dm_bulan_data { get; set; }
    public string dm_jenis_ljk { get; set; }
    public string dm_kode_ljk { get; set; }
    public string dm_nama_ljk { get; set; }
    public string dm_kode_kantor_cabang { get; set; }
    public string dm_nama_kantor_cabang { get; set; }
    public string dm_cif { get; set; }
    public string dm_no_rekening { get; set; }
    public string dm_no_identitas { get; set; }
    public string dm_nama_sesuai_identitas { get; set; }
    public Nullable<decimal> dm_plafon_awal { get; set; }
    public Nullable<decimal> dm_baki_debet { get; set; }
    public string dm_kode_jenis_kredit_pembiayaan { get; set; }
    public string dm_kode_jenis_penggunaan { get; set; }
    public Nullable<decimal> dm_suku_bunga_atau_imbalan { get; set; }
    public string dm_jenis_suku_bunga_atau_imbalan { get; set; }
    public string dm_jenis_debitur { get; set; }
    public string dm_segmen { get; set; }
    public string dm_kode_anomali { get; set; }
}

}