namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class da_anomali_nilai_agunan_deb
{
    public long rowid { get; set; }
    public System.DateTime dm_bulan_data { get; set; }
    public string dm_jenis_ljk { get; set; }
    public string dm_kode_ljk { get; set; }
    public string dm_kode_kantor_cabang { get; set; }
    public string dm_nama_ljk { get; set; }
    public string dm_cif { get; set; }
    public string dm_nama_id_debitur { get; set; }
    public string dm_no_id_debitur { get; set; }
    public string dm_no_rekening { get; set; }
    public string dm_kode_reg_agunan { get; set; }
    public Nullable<decimal> dm_baki_debet_nominal { get; set; }
    public Nullable<decimal> dm_nilai_agunan_menurut_pelapor { get; set; }
    public Nullable<decimal> dm_nilai_agunan_menurut_penilai_independen { get; set; }
    public string dm_penilai_independen { get; set; }
    public string dm_no_identitas_badan_usaha { get; set; }
    public string dm_nama_badan_usaha { get; set; }
    public string dm_jenis_badan_usaha { get; set; }
    public string dm_jenis_debitur { get; set; }
    public string dm_kode_anomali { get; set; }
    public string dm_nama_kantor_cabang { get; set; }
    public string dm_jenis_agunan { get; set; }
    public string dm_segmen { get; set; }
}

}