namespace BDA.DataModel
{//------------------------------------------------------------------------------
 // <auto-generated>
 //     This code was generated from a template.
 //
 //     Manual changes to this file may cause unexpected behavior in your application.
 //     Manual changes to this file will be overwritten if the code is regenerated.
 // </auto-generated>
 //------------------------------------------------------------------------------

    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;

    public partial class DataEntities : DbContext
    {
        public DataEntities()
            : base("name=DataEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<agunan_dokumen_anomali> agunan_dokumen_anomali { get; set; }
        public virtual DbSet<agunan_id_anomali> agunan_id_anomali { get; set; }
        public virtual DbSet<Alert_Master> Alert_Master { get; set; }
        public virtual DbSet<Alert_Summary> Alert_Summary { get; set; }
        public virtual DbSet<AuditTrail> AuditTrail { get; set; }
        public virtual DbSet<BDA_A01_Cluster> BDA_A01_Cluster { get; set; }
        public virtual DbSet<BDA_F01_MaxMinOverdue> BDA_F01_MaxMinOverdue { get; set; }
        public virtual DbSet<BDA_F01_Predictive> BDA_F01_Predictive { get; set; }
        public virtual DbSet<BDA_HML_MCDFA> BDA_HML_MCDFA { get; set; }
        public virtual DbSet<BDA_Log_PerHour> BDA_Log_PerHour { get; set; }
        public virtual DbSet<BDA_Log_PerMonth> BDA_Log_PerMonth { get; set; }
        public virtual DbSet<BDA_LogOutliers_Act> BDA_LogOutliers_Act { get; set; }
        public virtual DbSet<BDA_LogOutliers_Avg> BDA_LogOutliers_Avg { get; set; }
        public virtual DbSet<BDA2_Table> BDA2_Table { get; set; }
        public virtual DbSet<BDA2_Table_Period> BDA2_Table_Period { get; set; }
        public virtual DbSet<BDA2_Table_Period_LJK> BDA2_Table_Period_LJK { get; set; }
        public virtual DbSet<coverage_map_ljkxcity> coverage_map_ljkxcity { get; set; }
        public virtual DbSet<da_analisis_debtor_nom_identitas_beda> da_analisis_debtor_nom_identitas_beda { get; set; }
        public virtual DbSet<da_analisis_debtor_nom_identitas_sama> da_analisis_debtor_nom_identitas_sama { get; set; }
        public virtual DbSet<da_anomali_alamat_bekerja_debitur> da_anomali_alamat_bekerja_debitur { get; set; }
        public virtual DbSet<da_anomali_alamat_deb> da_anomali_alamat_deb { get; set; }
        public virtual DbSet<da_anomali_alamat_email_debitur> da_anomali_alamat_email_debitur { get; set; }
        public virtual DbSet<da_anomali_baki_debet_tidak_wajar> da_anomali_baki_debet_tidak_wajar { get; set; }
        public virtual DbSet<da_anomali_bentuk_badan_usaha> da_anomali_bentuk_badan_usaha { get; set; }
        public virtual DbSet<da_anomali_bukti_kepemilikan_agunan> da_anomali_bukti_kepemilikan_agunan { get; set; }
        public virtual DbSet<da_anomali_format_npwp> da_anomali_format_npwp { get; set; }
        public virtual DbSet<da_anomali_format_peringkat_agunan> da_anomali_format_peringkat_agunan { get; set; }
        public virtual DbSet<da_anomali_format_telepon_debitur> da_anomali_format_telepon_debitur { get; set; }
        public virtual DbSet<da_anomali_gelar_nama_deb> da_anomali_gelar_nama_deb { get; set; }
        public virtual DbSet<da_anomali_nama_ibu_kandung> da_anomali_nama_ibu_kandung { get; set; }
        public virtual DbSet<da_anomali_nik_deb> da_anomali_nik_deb { get; set; }
        public virtual DbSet<da_anomali_nik_lahir_debitur> da_anomali_nik_lahir_debitur { get; set; }
        public virtual DbSet<da_anomali_nilai_agunan_deb> da_anomali_nilai_agunan_deb { get; set; }
        public virtual DbSet<da_anomali_nilai_njop_agunan> da_anomali_nilai_njop_agunan { get; set; }
        public virtual DbSet<da_anomali_nomor_akta_badan_usaha> da_anomali_nomor_akta_badan_usaha { get; set; }
        public virtual DbSet<da_anomali_penghasilan_per_tahun> da_anomali_penghasilan_per_tahun { get; set; }
        public virtual DbSet<da_anomali_tempat_badan_usaha> da_anomali_tempat_badan_usaha { get; set; }
        public virtual DbSet<da_anomali_tempat_bekerja_debitur> da_anomali_tempat_bekerja_debitur { get; set; }
        public virtual DbSet<da_anomali_tempat_lahir_debitur> da_anomali_tempat_lahir_debitur { get; set; }
        public virtual DbSet<da_anomali_tingkat_suku_bunga> da_anomali_tingkat_suku_bunga { get; set; }
        public virtual DbSet<debitur_anomali_data_populasi> debitur_anomali_data_populasi { get; set; }
        public virtual DbSet<debitur_anomali_duplikasi_nama_debitur> debitur_anomali_duplikasi_nama_debitur { get; set; }
        public virtual DbSet<debitur_anomali_format_ktp> debitur_anomali_format_ktp { get; set; }
        public virtual DbSet<debitur_anomali_gender> debitur_anomali_gender { get; set; }
        public virtual DbSet<DimTanggal> DimTanggal { get; set; }
        public virtual DbSet<DimTime> DimTime { get; set; }
        public virtual DbSet<DxReport> DxReport { get; set; }
        public virtual DbSet<edge_collateral> edge_collateral { get; set; }
        public virtual DbSet<Email_In> Email_In { get; set; }
        public virtual DbSet<FWAttachment> FWAttachment { get; set; }
        public virtual DbSet<FWCalendar> FWCalendar { get; set; }
        public virtual DbSet<FWEmailQueue> FWEmailQueue { get; set; }
        public virtual DbSet<FWHoliday> FWHoliday { get; set; }
        public virtual DbSet<FWKodeCounter> FWKodeCounter { get; set; }
        public virtual DbSet<FWKodeDetail> FWKodeDetail { get; set; }
        public virtual DbSet<FWKodeFormat> FWKodeFormat { get; set; }
        public virtual DbSet<FWLOGError> FWLOGError { get; set; }
        public virtual DbSet<FWNotice> FWNotice { get; set; }
        public virtual DbSet<FWNoticeQueue> FWNoticeQueue { get; set; }
        public virtual DbSet<FWNoticeTemplate> FWNoticeTemplate { get; set; }
        public virtual DbSet<FWRefModul> FWRefModul { get; set; }
        public virtual DbSet<FWRefModulMenu> FWRefModulMenu { get; set; }
        public virtual DbSet<FWRefRole> FWRefRole { get; set; }
        public virtual DbSet<FWRefSetting> FWRefSetting { get; set; }
        public virtual DbSet<FWRoleRight> FWRoleRight { get; set; }
        public virtual DbSet<FWTempTable> FWTempTable { get; set; }
        public virtual DbSet<FWUserLostPassword> FWUserLostPassword { get; set; }
        public virtual DbSet<FWUserRole> FWUserRole { get; set; }
        public virtual DbSet<FWWorkday> FWWorkday { get; set; }
        public virtual DbSet<Glossary> Glossary { get; set; }
        public virtual DbSet<Help> Help { get; set; }
        public virtual DbSet<HiveSync> HiveSync { get; set; }
        public virtual DbSet<KonfigurasiAlert> KonfigurasiAlert { get; set; }
        public virtual DbSet<KonfigurasiALertDetail> KonfigurasiALertDetail { get; set; }
        public virtual DbSet<la_inquiry_check> la_inquiry_check { get; set; }
        public virtual DbSet<la_inquiry_pattern_recognition> la_inquiry_pattern_recognition { get; set; }
        public virtual DbSet<LOG_AKSES> LOG_AKSES { get; set; }
        public virtual DbSet<Log_ETL> Log_ETL { get; set; }
        public virtual DbSet<log_monitoring_bda_slik_det> log_monitoring_bda_slik_det { get; set; }
        public virtual DbSet<log_monitoring_bda_slik_sum> log_monitoring_bda_slik_sum { get; set; }
        public virtual DbSet<ma_aml_cft_analysis> ma_aml_cft_analysis { get; set; }
        public virtual DbSet<ma_analisis_pencurian_identitas> ma_analisis_pencurian_identitas { get; set; }
        public virtual DbSet<ma_anomali_plafon_by_pekerjaan_debitur> ma_anomali_plafon_by_pekerjaan_debitur { get; set; }
        public virtual DbSet<ma_kolektibilitas_kesalahan_ljk> ma_kolektibilitas_kesalahan_ljk { get; set; }
        public virtual DbSet<ma_outstanding_macet_no_agunan> ma_outstanding_macet_no_agunan { get; set; }
        public virtual DbSet<ma_rekening_baru_non_restrukturisasi_npl> ma_rekening_baru_non_restrukturisasi_npl { get; set; }
        public virtual DbSet<macro_output_forecast_level_ljk> macro_output_forecast_level_ljk { get; set; }
        public virtual DbSet<macro_penetrasi_lending_ljk> macro_penetrasi_lending_ljk { get; set; }
        public virtual DbSet<macro_pertumbuhan_pinjaman_level_ljk> macro_pertumbuhan_pinjaman_level_ljk { get; set; }
        public virtual DbSet<macro_policy_evaluation_analysis> macro_policy_evaluation_analysis { get; set; }
        public virtual DbSet<Master_Agunan> Master_Agunan { get; set; }
        public virtual DbSet<Master_Keterangan> Master_Keterangan { get; set; }
        public virtual DbSet<master_ljk> master_ljk { get; set; }
        public virtual DbSet<master_ljk_type> master_ljk_type { get; set; }
        public virtual DbSet<master_office_ljk> master_office_ljk { get; set; }
        public virtual DbSet<master_user_ideb> master_user_ideb { get; set; }
        public virtual DbSet<MasterKota> MasterKota { get; set; }
        public virtual DbSet<MasterPropinsi> MasterPropinsi { get; set; }
        public virtual DbSet<MasterSatker> MasterSatker { get; set; }
        public virtual DbSet<micro_credit_risk_analysis> micro_credit_risk_analysis { get; set; }
        public virtual DbSet<micro_plafond_usability_acc_detail> micro_plafond_usability_acc_detail { get; set; }
        public virtual DbSet<ms_ketentuan_kolektibilitas> ms_ketentuan_kolektibilitas { get; set; }
        public virtual DbSet<ms_kolektibilitas_karyawan_ljk> ms_kolektibilitas_karyawan_ljk { get; set; }
        public virtual DbSet<ms_pemberian_pinjaman_karyawan_ljk> ms_pemberian_pinjaman_karyawan_ljk { get; set; }
        public virtual DbSet<ms_perubahan_suku_bunga_no_restrukturisasi> ms_perubahan_suku_bunga_no_restrukturisasi { get; set; }
        public virtual DbSet<ms_pinjaman_baru_bersamaan_det> ms_pinjaman_baru_bersamaan_det { get; set; }
        public virtual DbSet<ms_pinjaman_baru_bersamaan_sum> ms_pinjaman_baru_bersamaan_sum { get; set; }
        public virtual DbSet<node_collateral> node_collateral { get; set; }
        public virtual DbSet<osida_agunan_tdk_dinilai_independen_det> osida_agunan_tdk_dinilai_independen_det { get; set; }
        public virtual DbSet<osida_agunan_tdk_dinilai_independen_mst> osida_agunan_tdk_dinilai_independen_mst { get; set; }
        public virtual DbSet<osida_alih_deb_ke_bank_det> osida_alih_deb_ke_bank_det { get; set; }
        public virtual DbSet<osida_alih_deb_ke_bank_mst> osida_alih_deb_ke_bank_mst { get; set; }
        public virtual DbSet<osida_hapusbuku_satu_tahun> osida_hapusbuku_satu_tahun { get; set; }
        public virtual DbSet<osida_info_keu_tdk_update_det> osida_info_keu_tdk_update_det { get; set; }
        public virtual DbSet<osida_info_keu_tdk_update_mst> osida_info_keu_tdk_update_mst { get; set; }
        public virtual DbSet<osida_keu_buruk_kol_lancar_det> osida_keu_buruk_kol_lancar_det { get; set; }
        public virtual DbSet<osida_keu_buruk_kol_lancar_mst> osida_keu_buruk_kol_lancar_mst { get; set; }
        public virtual DbSet<osida_kolektibilitas_hari_tunggakan> osida_kolektibilitas_hari_tunggakan { get; set; }
        public virtual DbSet<osida_kolektibilitas_jatuh_tempo> osida_kolektibilitas_jatuh_tempo { get; set; }
        public virtual DbSet<osida_kolektibilitas_nilai_tunggakan> osida_kolektibilitas_nilai_tunggakan { get; set; }
        public virtual DbSet<osida_kredit_macet_tdk_hb_det> osida_kredit_macet_tdk_hb_det { get; set; }
        public virtual DbSet<osida_kredit_macet_tdk_hb_mst> osida_kredit_macet_tdk_hb_mst { get; set; }
        public virtual DbSet<osida_kredit_melampaui_plafon> osida_kredit_melampaui_plafon { get; set; }
        public virtual DbSet<osida_kredit_no_agunan> osida_kredit_no_agunan { get; set; }
        public virtual DbSet<osida_kredit_takeover_macet> osida_kredit_takeover_macet { get; set; }
        public virtual DbSet<osida_kredit_takeover_tidak_bayar> osida_kredit_takeover_tidak_bayar { get; set; }
        public virtual DbSet<osida_master> osida_master { get; set; }
        public virtual DbSet<osida_nik_tidak_konsisten_det> osida_nik_tidak_konsisten_det { get; set; }
        public virtual DbSet<osida_nik_tidak_konsisten_mst> osida_nik_tidak_konsisten_mst { get; set; }
        public virtual DbSet<osida_pembanding_populasi_chart> osida_pembanding_populasi_chart { get; set; }
        public virtual DbSet<osida_pemberian_kur_deb_noneligible_det> osida_pemberian_kur_deb_noneligible_det { get; set; }
        public virtual DbSet<osida_pemberian_kur_deb_noneligible_mst> osida_pemberian_kur_deb_noneligible_mst { get; set; }
        public virtual DbSet<osida_pencairan_kredit_npl> osida_pencairan_kredit_npl { get; set; }
        public virtual DbSet<osida_pengurus_pemilik_kredit_bermasalah_det_bu> osida_pengurus_pemilik_kredit_bermasalah_det_bu { get; set; }
        public virtual DbSet<osida_pengurus_pemilik_kredit_bermasalah_det_pengurus> osida_pengurus_pemilik_kredit_bermasalah_det_pengurus { get; set; }
        public virtual DbSet<osida_pengurus_pemilik_kredit_bermasalah_mst> osida_pengurus_pemilik_kredit_bermasalah_mst { get; set; }
        public virtual DbSet<osida_perubahan_akad_no_restrukturisasi> osida_perubahan_akad_no_restrukturisasi { get; set; }
        public virtual DbSet<osida_plafondering_prk_dengan_plafon> osida_plafondering_prk_dengan_plafon { get; set; }
        public virtual DbSet<osida_plafondering_prk_tanpa_plafon> osida_plafondering_prk_tanpa_plafon { get; set; }
        public virtual DbSet<osida_plafondering_umum_detail> osida_plafondering_umum_detail { get; set; }
        public virtual DbSet<osida_plafondering_umum_master> osida_plafondering_umum_master { get; set; }
        public virtual DbSet<osida_potensi_konversi_kur_deb_noneligible_det> osida_potensi_konversi_kur_deb_noneligible_det { get; set; }
        public virtual DbSet<osida_potensi_konversi_kur_deb_noneligible_mst> osida_potensi_konversi_kur_deb_noneligible_mst { get; set; }
        public virtual DbSet<osida_restrukturisasi_satu_tahun> osida_restrukturisasi_satu_tahun { get; set; }
        public virtual DbSet<osida_tanpa_info_keu_det> osida_tanpa_info_keu_det { get; set; }
        public virtual DbSet<osida_tanpa_info_keu_mst> osida_tanpa_info_keu_mst { get; set; }
        public virtual DbSet<osida_tidak_bayar_dari_fasilitas_dibentuk> osida_tidak_bayar_dari_fasilitas_dibentuk { get; set; }
        public virtual DbSet<osint_edge_wordpair> osint_edge_wordpair { get; set; }
        public virtual DbSet<osint_node_wordpair> osint_node_wordpair { get; set; }
        public virtual DbSet<osint_scrapping_filtered> osint_scrapping_filtered { get; set; }
        public virtual DbSet<osint_tfidf_wordcloud> osint_tfidf_wordcloud { get; set; }
        public virtual DbSet<Penarikan_Data> Penarikan_Data { get; set; }
        public virtual DbSet<pengawas_ljk> pengawas_ljk { get; set; }
        public virtual DbSet<ref_cities> ref_cities { get; set; }
        public virtual DbSet<ref_collateral_types> ref_collateral_types { get; set; }
        public virtual DbSet<ref_credit_types> ref_credit_types { get; set; }
        public virtual DbSet<ref_credit_usages> ref_credit_usages { get; set; }
        public virtual DbSet<ref_ownership_document_temp> ref_ownership_document_temp { get; set; }
        public virtual DbSet<ref_pekerjaan_temp> ref_pekerjaan_temp { get; set; }
        public virtual DbSet<ReportDef> ReportDef { get; set; }
        public virtual DbSet<RptGrid> RptGrid { get; set; }
        public virtual DbSet<RptGrid_Param> RptGrid_Param { get; set; }
        public virtual DbSet<RptGrid_Queue> RptGrid_Queue { get; set; }
        public virtual DbSet<RptGrid_RoleSetting> RptGrid_RoleSetting { get; set; }
        public virtual DbSet<TableauLink> TableauLink { get; set; }
        public virtual DbSet<Thread> Thread { get; set; }
        public virtual DbSet<Thread_Post> Thread_Post { get; set; }
        public virtual DbSet<UserMaster> UserMaster { get; set; }
        public virtual DbSet<MEMBER_OFFICES> MEMBER_OFFICES { get; set; }
        public virtual DbSet<MEMBER_TYPES> MEMBER_TYPES { get; set; }
        public virtual DbSet<MEMBERS> MEMBERS { get; set; }
        public virtual DbSet<vw_getMasterLJK> vw_getMasterLJK { get; set; }
        public virtual DbSet<vw_getMasterOfficeLJK> vw_getMasterOfficeLJK { get; set; }
        public virtual DbSet<vw_JarakAntarAktivitas> vw_JarakAntarAktivitas { get; set; }
        public virtual DbSet<vw_ListUser> vw_ListUser { get; set; }
        public virtual DbSet<vw_Log_Akses> vw_Log_Akses { get; set; }
        public virtual DbSet<vw_Modul> vw_Modul { get; set; }
        public virtual DbSet<vw_PengawasLJK> vw_PengawasLJK { get; set; }
        public virtual DbSet<vw_PeriodTableHive> vw_PeriodTableHive { get; set; }
        public virtual DbSet<vw_RefDeskripsiKategori> vw_RefDeskripsiKategori { get; set; }
        public virtual DbSet<vw_TableDictionary> vw_TableDictionary { get; set; }

        //---------------------------------------------------------2024 BDAPM--------------------------------------------------------------------//
        public virtual DbSet<ip_sid> ip_sid { get; set; }
        public virtual DbSet<pe_segmentation_bridging_detail> pe_segmentation_bridging_detail { get; set; }
        public virtual DbSet<pe_segmentation_det_jaminan_margin> pe_segmentation_det_jaminan_margin { get; set; }
        public virtual DbSet<pe_segmentation_det_jaminan_margin_sum> pe_segmentation_det_jaminan_margin_sum { get; set; }
        public virtual DbSet<pe_segmentation_det_portofolio_saham> pe_segmentation_det_portofolio_saham { get; set; }
        public virtual DbSet<pe_segmentation_det_portofolio_saham_sum> pe_segmentation_det_portofolio_saham_sum { get; set; }
        public virtual DbSet<pe_segmentation_det_reksa_dana> pe_segmentation_det_reksa_dana { get; set; }
        public virtual DbSet<pe_segmentation_det_reksa_dana_sum> pe_segmentation_det_reksa_dana_sum { get; set; }
        public virtual DbSet<pe_segmentation_det_reverse_repo> pe_segmentation_det_reverse_repo { get; set; }
        public virtual DbSet<pe_segmentation_det_reverse_repo_sum> pe_segmentation_det_reverse_repo_sum { get; set; }
        public virtual DbSet<pe_segmentation_sum_cluster_mkbd> pe_segmentation_sum_cluster_mkbd { get; set; }
        public virtual DbSet<master_penggunaan_data> master_penggunaan_data { get; set; }
        //---------------------------------------------------------2024 BDAPM--------------------------------------------------------------------//

        public virtual ObjectResult<FW_userPermission_Result> FW_userPermission(string user_id, string mod_kode, string role_name)
        {
            var user_idParameter = user_id != null ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(string));

            var mod_kodeParameter = mod_kode != null ?
                new ObjectParameter("mod_kode", mod_kode) :
                new ObjectParameter("mod_kode", typeof(string));

            var role_nameParameter = role_name != null ?
                new ObjectParameter("role_name", role_name) :
                new ObjectParameter("role_name", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FW_userPermission_Result>("FW_userPermission", user_idParameter, mod_kodeParameter, role_nameParameter);
        }

        public virtual ObjectResult<PrintLongString_Result> PrintLongString(string str)
        {
            var strParameter = str != null ?
                new ObjectParameter("str", str) :
                new ObjectParameter("str", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PrintLongString_Result>("PrintLongString", strParameter);
        }

        public virtual ObjectResult<calendar_workday_Result> calendar_workday()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<calendar_workday_Result>("calendar_workday");
        }

        public virtual ObjectResult<CheckMatchLoginLogoutLog_Result> CheckMatchLoginLogoutLog()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CheckMatchLoginLogoutLog_Result>("CheckMatchLoginLogoutLog");
        }

        public virtual ObjectResult<getAlertSummary_Result> getAlertSummary(string kode_alert, string kode_alert_kategori, string level_alert, string jenis_ljk, string ljk, string office, string periode_awal, string periode_akhir, string datamart, string dimensi1, string dimensi2, string dimensi3, string dimensi4, string dimensi5)
        {
            var kode_alertParameter = kode_alert != null ?
                new ObjectParameter("kode_alert", kode_alert) :
                new ObjectParameter("kode_alert", typeof(string));

            var kode_alert_kategoriParameter = kode_alert_kategori != null ?
                new ObjectParameter("kode_alert_kategori", kode_alert_kategori) :
                new ObjectParameter("kode_alert_kategori", typeof(string));

            var level_alertParameter = level_alert != null ?
                new ObjectParameter("level_alert", level_alert) :
                new ObjectParameter("level_alert", typeof(string));

            var jenis_ljkParameter = jenis_ljk != null ?
                new ObjectParameter("jenis_ljk", jenis_ljk) :
                new ObjectParameter("jenis_ljk", typeof(string));

            var ljkParameter = ljk != null ?
                new ObjectParameter("ljk", ljk) :
                new ObjectParameter("ljk", typeof(string));

            var officeParameter = office != null ?
                new ObjectParameter("office", office) :
                new ObjectParameter("office", typeof(string));

            var periode_awalParameter = periode_awal != null ?
                new ObjectParameter("periode_awal", periode_awal) :
                new ObjectParameter("periode_awal", typeof(string));

            var periode_akhirParameter = periode_akhir != null ?
                new ObjectParameter("periode_akhir", periode_akhir) :
                new ObjectParameter("periode_akhir", typeof(string));

            var datamartParameter = datamart != null ?
                new ObjectParameter("datamart", datamart) :
                new ObjectParameter("datamart", typeof(string));

            var dimensi1Parameter = dimensi1 != null ?
                new ObjectParameter("dimensi1", dimensi1) :
                new ObjectParameter("dimensi1", typeof(string));

            var dimensi2Parameter = dimensi2 != null ?
                new ObjectParameter("dimensi2", dimensi2) :
                new ObjectParameter("dimensi2", typeof(string));

            var dimensi3Parameter = dimensi3 != null ?
                new ObjectParameter("dimensi3", dimensi3) :
                new ObjectParameter("dimensi3", typeof(string));

            var dimensi4Parameter = dimensi4 != null ?
                new ObjectParameter("dimensi4", dimensi4) :
                new ObjectParameter("dimensi4", typeof(string));

            var dimensi5Parameter = dimensi5 != null ?
                new ObjectParameter("dimensi5", dimensi5) :
                new ObjectParameter("dimensi5", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAlertSummary_Result>("getAlertSummary", kode_alertParameter, kode_alert_kategoriParameter, level_alertParameter, jenis_ljkParameter, ljkParameter, officeParameter, periode_awalParameter, periode_akhirParameter, datamartParameter, dimensi1Parameter, dimensi2Parameter, dimensi3Parameter, dimensi4Parameter, dimensi5Parameter);
        }

        public virtual ObjectResult<getAlertSummaryRJPOtherLJK_Result> getAlertSummaryRJPOtherLJK(string member_type_code, string member_code, string member_type_code2, string member_code2, string tipe_periode, string dimensi1, string dimensi2, Nullable<System.DateTime> periode_from, Nullable<System.DateTime> periode_until, string level_alert)
        {
            var member_type_codeParameter = member_type_code != null ?
                new ObjectParameter("member_type_code", member_type_code) :
                new ObjectParameter("member_type_code", typeof(string));

            var member_codeParameter = member_code != null ?
                new ObjectParameter("member_code", member_code) :
                new ObjectParameter("member_code", typeof(string));

            var member_type_code2Parameter = member_type_code2 != null ?
                new ObjectParameter("member_type_code2", member_type_code2) :
                new ObjectParameter("member_type_code2", typeof(string));

            var member_code2Parameter = member_code2 != null ?
                new ObjectParameter("member_code2", member_code2) :
                new ObjectParameter("member_code2", typeof(string));

            var tipe_periodeParameter = tipe_periode != null ?
                new ObjectParameter("tipe_periode", tipe_periode) :
                new ObjectParameter("tipe_periode", typeof(string));

            var dimensi1Parameter = dimensi1 != null ?
                new ObjectParameter("dimensi1", dimensi1) :
                new ObjectParameter("dimensi1", typeof(string));

            var dimensi2Parameter = dimensi2 != null ?
                new ObjectParameter("dimensi2", dimensi2) :
                new ObjectParameter("dimensi2", typeof(string));

            var periode_fromParameter = periode_from.HasValue ?
                new ObjectParameter("periode_from", periode_from) :
                new ObjectParameter("periode_from", typeof(System.DateTime));

            var periode_untilParameter = periode_until.HasValue ?
                new ObjectParameter("periode_until", periode_until) :
                new ObjectParameter("periode_until", typeof(System.DateTime));

            var level_alertParameter = level_alert != null ?
                new ObjectParameter("level_alert", level_alert) :
                new ObjectParameter("level_alert", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAlertSummaryRJPOtherLJK_Result>("getAlertSummaryRJPOtherLJK", member_type_codeParameter, member_codeParameter, member_type_code2Parameter, member_code2Parameter, tipe_periodeParameter, dimensi1Parameter, dimensi2Parameter, periode_fromParameter, periode_untilParameter, level_alertParameter);
        }

        public virtual ObjectResult<getColumnName_Result> getColumnName(string tblName)
        {
            var tblNameParameter = tblName != null ?
                new ObjectParameter("tblName", tblName) :
                new ObjectParameter("tblName", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getColumnName_Result>("getColumnName", tblNameParameter);
        }

        public virtual ObjectResult<GetDataAlert_Result> GetDataAlert(string userID, string lvlAlert, Nullable<System.DateTime> periode, string tipePeriode, string uID)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(string));

            var lvlAlertParameter = lvlAlert != null ?
                new ObjectParameter("lvlAlert", lvlAlert) :
                new ObjectParameter("lvlAlert", typeof(string));

            var periodeParameter = periode.HasValue ?
                new ObjectParameter("periode", periode) :
                new ObjectParameter("periode", typeof(System.DateTime));

            var tipePeriodeParameter = tipePeriode != null ?
                new ObjectParameter("tipePeriode", tipePeriode) :
                new ObjectParameter("tipePeriode", typeof(string));

            var uIDParameter = uID != null ?
                new ObjectParameter("uID", uID) :
                new ObjectParameter("uID", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDataAlert_Result>("GetDataAlert", userIDParameter, lvlAlertParameter, periodeParameter, tipePeriodeParameter, uIDParameter);
        }

        public virtual ObjectResult<getDataClaPredictive_Result> getDataClaPredictive(string periode_awal, string periode_akhir, string jenis_ljk, string ljk, string jenisDebitur, string statusCollectability, string dugaanCollectability)
        {
            var periode_awalParameter = periode_awal != null ?
                new ObjectParameter("periode_awal", periode_awal) :
                new ObjectParameter("periode_awal", typeof(string));

            var periode_akhirParameter = periode_akhir != null ?
                new ObjectParameter("periode_akhir", periode_akhir) :
                new ObjectParameter("periode_akhir", typeof(string));

            var jenis_ljkParameter = jenis_ljk != null ?
                new ObjectParameter("jenis_ljk", jenis_ljk) :
                new ObjectParameter("jenis_ljk", typeof(string));

            var ljkParameter = ljk != null ?
                new ObjectParameter("ljk", ljk) :
                new ObjectParameter("ljk", typeof(string));

            var jenisDebiturParameter = jenisDebitur != null ?
                new ObjectParameter("jenisDebitur", jenisDebitur) :
                new ObjectParameter("jenisDebitur", typeof(string));

            var statusCollectabilityParameter = statusCollectability != null ?
                new ObjectParameter("statusCollectability", statusCollectability) :
                new ObjectParameter("statusCollectability", typeof(string));

            var dugaanCollectabilityParameter = dugaanCollectability != null ?
                new ObjectParameter("dugaanCollectability", dugaanCollectability) :
                new ObjectParameter("dugaanCollectability", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getDataClaPredictive_Result>("getDataClaPredictive", periode_awalParameter, periode_akhirParameter, jenis_ljkParameter, ljkParameter, jenisDebiturParameter, statusCollectabilityParameter, dugaanCollectabilityParameter);
        }

        public virtual ObjectResult<getDataCluster_Result> getDataCluster(string periode_awal, string periode_akhir, string jenis_ljk, string ljk, string jenisAgunan, string cluster, string chart)
        {
            var periode_awalParameter = periode_awal != null ?
                new ObjectParameter("periode_awal", periode_awal) :
                new ObjectParameter("periode_awal", typeof(string));

            var periode_akhirParameter = periode_akhir != null ?
                new ObjectParameter("periode_akhir", periode_akhir) :
                new ObjectParameter("periode_akhir", typeof(string));

            var jenis_ljkParameter = jenis_ljk != null ?
                new ObjectParameter("jenis_ljk", jenis_ljk) :
                new ObjectParameter("jenis_ljk", typeof(string));

            var ljkParameter = ljk != null ?
                new ObjectParameter("ljk", ljk) :
                new ObjectParameter("ljk", typeof(string));

            var jenisAgunanParameter = jenisAgunan != null ?
                new ObjectParameter("JenisAgunan", jenisAgunan) :
                new ObjectParameter("JenisAgunan", typeof(string));

            var clusterParameter = cluster != null ?
                new ObjectParameter("Cluster", cluster) :
                new ObjectParameter("Cluster", typeof(string));

            var chartParameter = chart != null ?
                new ObjectParameter("chart", chart) :
                new ObjectParameter("chart", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getDataCluster_Result>("getDataCluster", periode_awalParameter, periode_akhirParameter, jenis_ljkParameter, ljkParameter, jenisAgunanParameter, clusterParameter, chartParameter);
        }

        public virtual ObjectResult<getDataMMOverdue_Result> getDataMMOverdue(string periode_awal, string periode_akhir, string jenis_ljk, string ljk, string jenisDebitur, string statusCollectability)
        {
            var periode_awalParameter = periode_awal != null ?
                new ObjectParameter("periode_awal", periode_awal) :
                new ObjectParameter("periode_awal", typeof(string));

            var periode_akhirParameter = periode_akhir != null ?
                new ObjectParameter("periode_akhir", periode_akhir) :
                new ObjectParameter("periode_akhir", typeof(string));

            var jenis_ljkParameter = jenis_ljk != null ?
                new ObjectParameter("jenis_ljk", jenis_ljk) :
                new ObjectParameter("jenis_ljk", typeof(string));

            var ljkParameter = ljk != null ?
                new ObjectParameter("ljk", ljk) :
                new ObjectParameter("ljk", typeof(string));

            var jenisDebiturParameter = jenisDebitur != null ?
                new ObjectParameter("jenisDebitur", jenisDebitur) :
                new ObjectParameter("jenisDebitur", typeof(string));

            var statusCollectabilityParameter = statusCollectability != null ?
                new ObjectParameter("statusCollectability", statusCollectability) :
                new ObjectParameter("statusCollectability", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getDataMMOverdue_Result>("getDataMMOverdue", periode_awalParameter, periode_akhirParameter, jenis_ljkParameter, ljkParameter, jenisDebiturParameter, statusCollectabilityParameter);
        }

        public virtual ObjectResult<getGroupedAlertSummary_Result> getGroupedAlertSummary(string kode_alert, string kode_alert_kategori, string level_alert, string jenis_ljk, string ljk, string office, string periode_awal, string periode_akhir, string datamart, string dimensi1, string dimensi2, string dimensi3, string dimensi4, string dimensi5)
        {
            var kode_alertParameter = kode_alert != null ?
                new ObjectParameter("kode_alert", kode_alert) :
                new ObjectParameter("kode_alert", typeof(string));

            var kode_alert_kategoriParameter = kode_alert_kategori != null ?
                new ObjectParameter("kode_alert_kategori", kode_alert_kategori) :
                new ObjectParameter("kode_alert_kategori", typeof(string));

            var level_alertParameter = level_alert != null ?
                new ObjectParameter("level_alert", level_alert) :
                new ObjectParameter("level_alert", typeof(string));

            var jenis_ljkParameter = jenis_ljk != null ?
                new ObjectParameter("jenis_ljk", jenis_ljk) :
                new ObjectParameter("jenis_ljk", typeof(string));

            var ljkParameter = ljk != null ?
                new ObjectParameter("ljk", ljk) :
                new ObjectParameter("ljk", typeof(string));

            var officeParameter = office != null ?
                new ObjectParameter("office", office) :
                new ObjectParameter("office", typeof(string));

            var periode_awalParameter = periode_awal != null ?
                new ObjectParameter("periode_awal", periode_awal) :
                new ObjectParameter("periode_awal", typeof(string));

            var periode_akhirParameter = periode_akhir != null ?
                new ObjectParameter("periode_akhir", periode_akhir) :
                new ObjectParameter("periode_akhir", typeof(string));

            var datamartParameter = datamart != null ?
                new ObjectParameter("datamart", datamart) :
                new ObjectParameter("datamart", typeof(string));

            var dimensi1Parameter = dimensi1 != null ?
                new ObjectParameter("dimensi1", dimensi1) :
                new ObjectParameter("dimensi1", typeof(string));

            var dimensi2Parameter = dimensi2 != null ?
                new ObjectParameter("dimensi2", dimensi2) :
                new ObjectParameter("dimensi2", typeof(string));

            var dimensi3Parameter = dimensi3 != null ?
                new ObjectParameter("dimensi3", dimensi3) :
                new ObjectParameter("dimensi3", typeof(string));

            var dimensi4Parameter = dimensi4 != null ?
                new ObjectParameter("dimensi4", dimensi4) :
                new ObjectParameter("dimensi4", typeof(string));

            var dimensi5Parameter = dimensi5 != null ?
                new ObjectParameter("dimensi5", dimensi5) :
                new ObjectParameter("dimensi5", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getGroupedAlertSummary_Result>("getGroupedAlertSummary", kode_alertParameter, kode_alert_kategoriParameter, level_alertParameter, jenis_ljkParameter, ljkParameter, officeParameter, periode_awalParameter, periode_akhirParameter, datamartParameter, dimensi1Parameter, dimensi2Parameter, dimensi3Parameter, dimensi4Parameter, dimensi5Parameter);
        }

        public virtual ObjectResult<getGroupedRJPOtherLJK_Result> getGroupedRJPOtherLJK(string member_type_code, string member_code, string member_type_code2, string member_code2, string tipe_periode, string dimensi1, string dimensi2, Nullable<System.DateTime> periode_from, Nullable<System.DateTime> periode_until, string level_alert)
        {
            var member_type_codeParameter = member_type_code != null ?
                new ObjectParameter("member_type_code", member_type_code) :
                new ObjectParameter("member_type_code", typeof(string));

            var member_codeParameter = member_code != null ?
                new ObjectParameter("member_code", member_code) :
                new ObjectParameter("member_code", typeof(string));

            var member_type_code2Parameter = member_type_code2 != null ?
                new ObjectParameter("member_type_code2", member_type_code2) :
                new ObjectParameter("member_type_code2", typeof(string));

            var member_code2Parameter = member_code2 != null ?
                new ObjectParameter("member_code2", member_code2) :
                new ObjectParameter("member_code2", typeof(string));

            var tipe_periodeParameter = tipe_periode != null ?
                new ObjectParameter("tipe_periode", tipe_periode) :
                new ObjectParameter("tipe_periode", typeof(string));

            var dimensi1Parameter = dimensi1 != null ?
                new ObjectParameter("dimensi1", dimensi1) :
                new ObjectParameter("dimensi1", typeof(string));

            var dimensi2Parameter = dimensi2 != null ?
                new ObjectParameter("dimensi2", dimensi2) :
                new ObjectParameter("dimensi2", typeof(string));

            var periode_fromParameter = periode_from.HasValue ?
                new ObjectParameter("periode_from", periode_from) :
                new ObjectParameter("periode_from", typeof(System.DateTime));

            var periode_untilParameter = periode_until.HasValue ?
                new ObjectParameter("periode_until", periode_until) :
                new ObjectParameter("periode_until", typeof(System.DateTime));

            var level_alertParameter = level_alert != null ?
                new ObjectParameter("level_alert", level_alert) :
                new ObjectParameter("level_alert", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getGroupedRJPOtherLJK_Result>("getGroupedRJPOtherLJK", member_type_codeParameter, member_codeParameter, member_type_code2Parameter, member_code2Parameter, tipe_periodeParameter, dimensi1Parameter, dimensi2Parameter, periode_fromParameter, periode_untilParameter, level_alertParameter);
        }

        public virtual ObjectResult<getHmlMcdfa_Result> getHmlMcdfa(string tipe_dashboard, string kode_report, string jenis_ljk, string ljk, string hml, string mcdfa, string periode_awal, string periode_akhir, string dimensi1)
        {
            var tipe_dashboardParameter = tipe_dashboard != null ?
                new ObjectParameter("tipe_dashboard", tipe_dashboard) :
                new ObjectParameter("tipe_dashboard", typeof(string));

            var kode_reportParameter = kode_report != null ?
                new ObjectParameter("kode_report", kode_report) :
                new ObjectParameter("kode_report", typeof(string));

            var jenis_ljkParameter = jenis_ljk != null ?
                new ObjectParameter("jenis_ljk", jenis_ljk) :
                new ObjectParameter("jenis_ljk", typeof(string));

            var ljkParameter = ljk != null ?
                new ObjectParameter("ljk", ljk) :
                new ObjectParameter("ljk", typeof(string));

            var hmlParameter = hml != null ?
                new ObjectParameter("hml", hml) :
                new ObjectParameter("hml", typeof(string));

            var mcdfaParameter = mcdfa != null ?
                new ObjectParameter("mcdfa", mcdfa) :
                new ObjectParameter("mcdfa", typeof(string));

            var periode_awalParameter = periode_awal != null ?
                new ObjectParameter("periode_awal", periode_awal) :
                new ObjectParameter("periode_awal", typeof(string));

            var periode_akhirParameter = periode_akhir != null ?
                new ObjectParameter("periode_akhir", periode_akhir) :
                new ObjectParameter("periode_akhir", typeof(string));

            var dimensi1Parameter = dimensi1 != null ?
                new ObjectParameter("dimensi1", dimensi1) :
                new ObjectParameter("dimensi1", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getHmlMcdfa_Result>("getHmlMcdfa", tipe_dashboardParameter, kode_reportParameter, jenis_ljkParameter, ljkParameter, hmlParameter, mcdfaParameter, periode_awalParameter, periode_akhirParameter, dimensi1Parameter);
        }

        public virtual ObjectResult<getListMenu_Result> getListMenu(string tipe)
        {
            var tipeParameter = tipe != null ?
                new ObjectParameter("tipe", tipe) :
                new ObjectParameter("tipe", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getListMenu_Result>("getListMenu", tipeParameter);
        }

        public virtual ObjectResult<getListQueue_Result> getListQueue()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getListQueue_Result>("getListQueue");
        }

        public virtual ObjectResult<getListUserPengawasForDelete_Result> getListUserPengawasForDelete()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getListUserPengawasForDelete_Result>("getListUserPengawasForDelete");
        }

        public virtual ObjectResult<getListUserSync_Result> getListUserSync()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getListUserSync_Result>("getListUserSync");
        }

        public virtual ObjectResult<getLJKPengawas_Result> getLJKPengawas(string userID)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getLJKPengawas_Result>("getLJKPengawas", userIDParameter);
        }

        public virtual ObjectResult<getLogOutliers_Result> getLogOutliers(string jenis_ljk, string ljk, string periode_awal, string periode_akhir)
        {
            var jenis_ljkParameter = jenis_ljk != null ?
                new ObjectParameter("jenis_ljk", jenis_ljk) :
                new ObjectParameter("jenis_ljk", typeof(string));

            var ljkParameter = ljk != null ?
                new ObjectParameter("ljk", ljk) :
                new ObjectParameter("ljk", typeof(string));

            var periode_awalParameter = periode_awal != null ?
                new ObjectParameter("periode_awal", periode_awal) :
                new ObjectParameter("periode_awal", typeof(string));

            var periode_akhirParameter = periode_akhir != null ?
                new ObjectParameter("periode_akhir", periode_akhir) :
                new ObjectParameter("periode_akhir", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getLogOutliers_Result>("getLogOutliers", jenis_ljkParameter, ljkParameter, periode_awalParameter, periode_akhirParameter);
        }

        public virtual ObjectResult<getLogOutliersAvg_Result> getLogOutliersAvg(string jenis_ljk, string ljk, string periode_awal, string periode_akhir, string status)
        {
            var jenis_ljkParameter = jenis_ljk != null ?
                new ObjectParameter("jenis_ljk", jenis_ljk) :
                new ObjectParameter("jenis_ljk", typeof(string));

            var ljkParameter = ljk != null ?
                new ObjectParameter("ljk", ljk) :
                new ObjectParameter("ljk", typeof(string));

            var periode_awalParameter = periode_awal != null ?
                new ObjectParameter("periode_awal", periode_awal) :
                new ObjectParameter("periode_awal", typeof(string));

            var periode_akhirParameter = periode_akhir != null ?
                new ObjectParameter("periode_akhir", periode_akhir) :
                new ObjectParameter("periode_akhir", typeof(string));

            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getLogOutliersAvg_Result>("getLogOutliersAvg", jenis_ljkParameter, ljkParameter, periode_awalParameter, periode_akhirParameter, statusParameter);
        }

        public virtual ObjectResult<getLogOutliersAvgKomposisi_Result> getLogOutliersAvgKomposisi(string jenis_ljk, string ljk, string periode_awal, string periode_akhir)
        {
            var jenis_ljkParameter = jenis_ljk != null ?
                new ObjectParameter("jenis_ljk", jenis_ljk) :
                new ObjectParameter("jenis_ljk", typeof(string));

            var ljkParameter = ljk != null ?
                new ObjectParameter("ljk", ljk) :
                new ObjectParameter("ljk", typeof(string));

            var periode_awalParameter = periode_awal != null ?
                new ObjectParameter("periode_awal", periode_awal) :
                new ObjectParameter("periode_awal", typeof(string));

            var periode_akhirParameter = periode_akhir != null ?
                new ObjectParameter("periode_akhir", periode_akhir) :
                new ObjectParameter("periode_akhir", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getLogOutliersAvgKomposisi_Result>("getLogOutliersAvgKomposisi", jenis_ljkParameter, ljkParameter, periode_awalParameter, periode_akhirParameter);
        }

        public virtual ObjectResult<getLogOutliersDetail_Result> getLogOutliersDetail(string jenis_ljk, string ljk, string periode_awal, string periode_akhir, string status)
        {
            var jenis_ljkParameter = jenis_ljk != null ?
                new ObjectParameter("jenis_ljk", jenis_ljk) :
                new ObjectParameter("jenis_ljk", typeof(string));

            var ljkParameter = ljk != null ?
                new ObjectParameter("ljk", ljk) :
                new ObjectParameter("ljk", typeof(string));

            var periode_awalParameter = periode_awal != null ?
                new ObjectParameter("periode_awal", periode_awal) :
                new ObjectParameter("periode_awal", typeof(string));

            var periode_akhirParameter = periode_akhir != null ?
                new ObjectParameter("periode_akhir", periode_akhir) :
                new ObjectParameter("periode_akhir", typeof(string));

            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getLogOutliersDetail_Result>("getLogOutliersDetail", jenis_ljkParameter, ljkParameter, periode_awalParameter, periode_akhirParameter, statusParameter);
        }

        public virtual ObjectResult<getLogPerHour_Result> getLogPerHour(string jenis_ljk, string ljk, string periode)
        {
            var jenis_ljkParameter = jenis_ljk != null ?
                new ObjectParameter("jenis_ljk", jenis_ljk) :
                new ObjectParameter("jenis_ljk", typeof(string));

            var ljkParameter = ljk != null ?
                new ObjectParameter("ljk", ljk) :
                new ObjectParameter("ljk", typeof(string));

            var periodeParameter = periode != null ?
                new ObjectParameter("periode", periode) :
                new ObjectParameter("periode", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getLogPerHour_Result>("getLogPerHour", jenis_ljkParameter, ljkParameter, periodeParameter);
        }

        public virtual ObjectResult<getLogPerMonth_Result> getLogPerMonth(string jenis_ljk, string ljk, string periode_awal, string periode_akhir)
        {
            var jenis_ljkParameter = jenis_ljk != null ?
                new ObjectParameter("jenis_ljk", jenis_ljk) :
                new ObjectParameter("jenis_ljk", typeof(string));

            var ljkParameter = ljk != null ?
                new ObjectParameter("ljk", ljk) :
                new ObjectParameter("ljk", typeof(string));

            var periode_awalParameter = periode_awal != null ?
                new ObjectParameter("periode_awal", periode_awal) :
                new ObjectParameter("periode_awal", typeof(string));

            var periode_akhirParameter = periode_akhir != null ?
                new ObjectParameter("periode_akhir", periode_akhir) :
                new ObjectParameter("periode_akhir", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getLogPerMonth_Result>("getLogPerMonth", jenis_ljkParameter, ljkParameter, periode_awalParameter, periode_akhirParameter);
        }

        public virtual ObjectResult<getMenuDb_Result> getMenuDb(string user_id, string role_name)
        {
            var user_idParameter = user_id != null ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(string));

            var role_nameParameter = role_name != null ?
                new ObjectParameter("role_name", role_name) :
                new ObjectParameter("role_name", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getMenuDb_Result>("getMenuDb", user_idParameter, role_nameParameter);
        }

        public virtual ObjectResult<getModulChildren_Result> getModulChildren(Nullable<long> node_id)
        {
            var node_idParameter = node_id.HasValue ?
                new ObjectParameter("node_id", node_id) :
                new ObjectParameter("node_id", typeof(long));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getModulChildren_Result>("getModulChildren", node_idParameter);
        }

        public virtual ObjectResult<getNotification_Result> getNotification(string user_id)
        {
            var user_idParameter = user_id != null ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getNotification_Result>("getNotification", user_idParameter);
        }

        public virtual ObjectResult<getPengawasDailyALert_Result> getPengawasDailyALert(Nullable<System.DateTime> periode, string tipePeriode)
        {
            var periodeParameter = periode.HasValue ?
                new ObjectParameter("periode", periode) :
                new ObjectParameter("periode", typeof(System.DateTime));

            var tipePeriodeParameter = tipePeriode != null ?
                new ObjectParameter("tipePeriode", tipePeriode) :
                new ObjectParameter("tipePeriode", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getPengawasDailyALert_Result>("getPengawasDailyALert", periodeParameter, tipePeriodeParameter);
        }

        public virtual ObjectResult<getRJPSelfVsOtherLJK_Result> getRJPSelfVsOtherLJK(string member_type_code, string member_code, string member_type_code2, string member_code2, string tipe_periode, string dimensi1, string dimensi2, Nullable<System.DateTime> periode_from, Nullable<System.DateTime> periode_until)
        {
            var member_type_codeParameter = member_type_code != null ?
                new ObjectParameter("member_type_code", member_type_code) :
                new ObjectParameter("member_type_code", typeof(string));

            var member_codeParameter = member_code != null ?
                new ObjectParameter("member_code", member_code) :
                new ObjectParameter("member_code", typeof(string));

            var member_type_code2Parameter = member_type_code2 != null ?
                new ObjectParameter("member_type_code2", member_type_code2) :
                new ObjectParameter("member_type_code2", typeof(string));

            var member_code2Parameter = member_code2 != null ?
                new ObjectParameter("member_code2", member_code2) :
                new ObjectParameter("member_code2", typeof(string));

            var tipe_periodeParameter = tipe_periode != null ?
                new ObjectParameter("tipe_periode", tipe_periode) :
                new ObjectParameter("tipe_periode", typeof(string));

            var dimensi1Parameter = dimensi1 != null ?
                new ObjectParameter("dimensi1", dimensi1) :
                new ObjectParameter("dimensi1", typeof(string));

            var dimensi2Parameter = dimensi2 != null ?
                new ObjectParameter("dimensi2", dimensi2) :
                new ObjectParameter("dimensi2", typeof(string));

            var periode_fromParameter = periode_from.HasValue ?
                new ObjectParameter("periode_from", periode_from) :
                new ObjectParameter("periode_from", typeof(System.DateTime));

            var periode_untilParameter = periode_until.HasValue ?
                new ObjectParameter("periode_until", periode_until) :
                new ObjectParameter("periode_until", typeof(System.DateTime));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getRJPSelfVsOtherLJK_Result>("getRJPSelfVsOtherLJK", member_type_codeParameter, member_codeParameter, member_type_code2Parameter, member_code2Parameter, tipe_periodeParameter, dimensi1Parameter, dimensi2Parameter, periode_fromParameter, periode_untilParameter);
        }

        public virtual ObjectResult<getRoleEmail_Result> getRoleEmail(string roleCsv)
        {
            var roleCsvParameter = roleCsv != null ?
                new ObjectParameter("roleCsv", roleCsv) :
                new ObjectParameter("roleCsv", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getRoleEmail_Result>("getRoleEmail", roleCsvParameter);
        }

        public virtual ObjectResult<getRoleWithSatkerEmail_Result> getRoleWithSatkerEmail(string roleCsv, Nullable<long> satker_id)
        {
            var roleCsvParameter = roleCsv != null ?
                new ObjectParameter("roleCsv", roleCsv) :
                new ObjectParameter("roleCsv", typeof(string));

            var satker_idParameter = satker_id.HasValue ?
                new ObjectParameter("satker_id", satker_id) :
                new ObjectParameter("satker_id", typeof(long));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getRoleWithSatkerEmail_Result>("getRoleWithSatkerEmail", roleCsvParameter, satker_idParameter);
        }

        public virtual ObjectResult<getSummaryJenisLJK_Result> getSummaryJenisLJK(string selectedDQ, string jenisLJK, string period)
        {
            var selectedDQParameter = selectedDQ != null ?
                new ObjectParameter("SelectedDQ", selectedDQ) :
                new ObjectParameter("SelectedDQ", typeof(string));

            var jenisLJKParameter = jenisLJK != null ?
                new ObjectParameter("JenisLJK", jenisLJK) :
                new ObjectParameter("JenisLJK", typeof(string));

            var periodParameter = period != null ?
                new ObjectParameter("Period", period) :
                new ObjectParameter("Period", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getSummaryJenisLJK_Result>("getSummaryJenisLJK", selectedDQParameter, jenisLJKParameter, periodParameter);
        }

        public virtual ObjectResult<getSummaryLJK_Result> getSummaryLJK(string jenisLJK, string kodeLJK, string period)
        {
            var jenisLJKParameter = jenisLJK != null ?
                new ObjectParameter("JenisLJK", jenisLJK) :
                new ObjectParameter("JenisLJK", typeof(string));

            var kodeLJKParameter = kodeLJK != null ?
                new ObjectParameter("KodeLJK", kodeLJK) :
                new ObjectParameter("KodeLJK", typeof(string));

            var periodParameter = period != null ?
                new ObjectParameter("Period", period) :
                new ObjectParameter("Period", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getSummaryLJK_Result>("getSummaryLJK", jenisLJKParameter, kodeLJKParameter, periodParameter);
        }

        public virtual ObjectResult<getSummaryRowTable_Result> getSummaryRowTable(Nullable<System.DateTime> period, string tipe, string jenis_ljk, string ljk)
        {
            var periodParameter = period.HasValue ?
                new ObjectParameter("period", period) :
                new ObjectParameter("period", typeof(System.DateTime));

            var tipeParameter = tipe != null ?
                new ObjectParameter("tipe", tipe) :
                new ObjectParameter("tipe", typeof(string));

            var jenis_ljkParameter = jenis_ljk != null ?
                new ObjectParameter("jenis_ljk", jenis_ljk) :
                new ObjectParameter("jenis_ljk", typeof(string));

            var ljkParameter = ljk != null ?
                new ObjectParameter("ljk", ljk) :
                new ObjectParameter("ljk", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getSummaryRowTable_Result>("getSummaryRowTable", periodParameter, tipeParameter, jenis_ljkParameter, ljkParameter);
        }

        public virtual ObjectResult<getTotalPelapor_Result> getTotalPelapor(string userID)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getTotalPelapor_Result>("getTotalPelapor", userIDParameter);
        }

        public virtual ObjectResult<updSBPembandingFromRJPSeflBulanan_Result> updSBPembandingFromRJPSeflBulanan(Nullable<System.DateTime> periode_from)
        {
            var periode_fromParameter = periode_from.HasValue ?
                new ObjectParameter("periode_from", periode_from) :
                new ObjectParameter("periode_from", typeof(System.DateTime));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<updSBPembandingFromRJPSeflBulanan_Result>("updSBPembandingFromRJPSeflBulanan", periode_fromParameter);
        }
    }

}