namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class debitur_anomali_duplikasi_nama_debitur
{
    public System.DateTime dm_periode { get; set; }
    public long rowid { get; set; }
    public string dm_jenis_ljk { get; set; }
    public string dm_kode_ljk { get; set; }
    public string dm_cif { get; set; }
    public string dm_nama_debitur { get; set; }
    public string dm_kode_jenis_identitas_debitur { get; set; }
    public string dm_no_id_debitur { get; set; }
    public string dm_nama_id_debitur { get; set; }
    public string dm_tanggal_lahir { get; set; }
    public string dm_nama_ibu_kandung { get; set; }
    public string dm_status_valid_id_debitur { get; set; }
    public Nullable<double> dm_similarity_score { get; set; }
    public string dm_similarity_result { get; set; }
    public string dm_identity_number_name_1 { get; set; }
    public string dm_tanggal_lahir_1 { get; set; }
    public string dm_nama_ibu_kandung_1 { get; set; }
    public Nullable<double> dm_similarity_threshold { get; set; }
    public string dm_final_similarity_method { get; set; }
    public string dm_jenis_ljk_1 { get; set; }
    public string dm_kode_ljk_1 { get; set; }
    public string dm_cif_1 { get; set; }
}

}