namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class dim_exchange_members
{
    public string exchangemembersk { get; set; }
    public string exchangemembercode { get; set; }
    public string exchangememberid { get; set; }
    public string exchangemembername { get; set; }
    public string spabno { get; set; }
    public Nullable<System.DateTime> spabdate { get; set; }
    public string licenseno { get; set; }
    public string shareno { get; set; }
    public Nullable<System.DateTime> transactiondate { get; set; }
    public string internalcode { get; set; }
    public string reinfocode { get; set; }
    public Nullable<System.DateTime> statusdate { get; set; }
    public string currentstatus { get; set; }
    public string emcapitalsourcetypesk { get; set; }
    public string emcapitalsourcetypecode { get; set; }
    public string emtransactionmethodsk { get; set; }
    public string emtransactionmethodcode { get; set; }
    public string effectivedatesk { get; set; }
    public Nullable<System.DateTime> effectivedate { get; set; }
    public string enddatesk { get; set; }
    public Nullable<System.DateTime> enddate { get; set; }
    public string emoperationalstatussk { get; set; }
    public string emoperationalstatuscode { get; set; }
    public string companylogoimageurl { get; set; }
}

}