namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class DxReport
{
    public string DxRepKode { get; set; }
    public string DxRepTipe { get; set; }
    public string DxRepNama { get; set; }
    public byte[] DxRepXml { get; set; }
}

}