namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class edge_collateral
{
    public System.DateTime dm_periode { get; set; }
    public long rowid { get; set; }
    public string dm_relationship { get; set; }
    public string dm_first_node_id { get; set; }
    public string dm_second_node_id { get; set; }
    public string dm_relationship_status { get; set; }
    public Nullable<int> dm_number_of_facility_type { get; set; }
    public string dm_has_joint_credit { get; set; }
    public Nullable<long> dm_number_of_associated_rel { get; set; }
    public Nullable<long> dm_number_of_active_associated_rel { get; set; }
    public Nullable<decimal> dm_estimated_subtotal_active_collateral_value { get; set; }
    public Nullable<decimal> dm_estimated_subtotal_active_joint_collateral_value { get; set; }
    public Nullable<decimal> dm_active_outstanding { get; set; }
    public Nullable<decimal> dm_active_joint_outstanding { get; set; }
    public Nullable<double> dm_edge_width_factor { get; set; }
    public Nullable<double> dm_edge_color_factor { get; set; }
}

}