namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class FWAttachment
{
    public long AttachId { get; set; }
    public System.Guid AttachObjId { get; set; }
    public string AttachTipe { get; set; }
    public string AttachKode { get; set; }
    public byte[] AttachThumb { get; set; }
    public string AttachFileNama { get; set; }
    public int AttachFileSize { get; set; }
    public string AttachFileLink { get; set; }
    public string AttachFilePwd { get; set; }
    public string Stsrc { get; set; }
    public string CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDatetime { get; set; }
    public string UpdatedBy { get; set; }
    public Nullable<System.DateTime> UpdatedDatetime { get; set; }
    public Nullable<long> HelpId { get; set; }
    public Nullable<long> PostId { get; set; }
    public Nullable<long> EminId { get; set; }

    public virtual Email_In Email_In { get; set; }
    public virtual Help Help { get; set; }
    public virtual Thread_Post Thread_Post { get; set; }
}

}