namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class FWKodeCounter
{
    public long KdcnId { get; set; }
    public string KofId { get; set; }
    public string KdcnPrefix { get; set; }
    public int KdcnCounter { get; set; }
    public string KdcnLast { get; set; }
    public System.DateTime KdcnLastUpdate { get; set; }
    public System.DateTime KdcnLastReset { get; set; }

    public virtual FWKodeFormat FWKodeFormat { get; set; }
}

}