namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class FWKodeFormat
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public FWKodeFormat()
    {
        this.FWKodeCounter = new HashSet<FWKodeCounter>();
        this.FWKodeDetail = new HashSet<FWKodeDetail>();
    }

    public string KofId { get; set; }
    public byte KofCounterLength { get; set; }
    public byte KofIncrement { get; set; }
    public int KofStart { get; set; }
    public string KofCatatan { get; set; }
    public string KofResetTp { get; set; }
    public int KofResetInterval { get; set; }
    public System.DateTime KofResetTime { get; set; }
    public string Stsrc { get; set; }
    public string CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDatetime { get; set; }
    public string UpdatedBy { get; set; }
    public Nullable<System.DateTime> UpdatedDatetime { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<FWKodeCounter> FWKodeCounter { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<FWKodeDetail> FWKodeDetail { get; set; }
}

}