namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class FWNoticeTemplate
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public FWNoticeTemplate()
    {
        this.FWNotice = new HashSet<FWNotice>();
        this.FWNoticeQueue = new HashSet<FWNoticeQueue>();
    }

    public string NottId { get; set; }
    public string NottTitle { get; set; }
    public string NottGroup { get; set; }
    public string NottTo { get; set; }
    public string NottCc { get; set; }
    public string NottBcc { get; set; }
    public string NottBatch { get; set; }
    public string NottSender { get; set; }
    public string NottContent { get; set; }
    public string NottCatatan { get; set; }
    public bool NottOneEmailPerUser { get; set; }
    public string NottRefId { get; set; }
    public string NottRefId2 { get; set; }
    public string NottRefId3 { get; set; }
    public string NottModelType { get; set; }
    public string NottKeyType { get; set; }
    public string NottLastTestId { get; set; }
    public string NottSmallContent { get; set; }
    public string RdefKode { get; set; }
    public string NottRdefParamCsv { get; set; }
    public string Stsrc { get; set; }
    public string CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDatetime { get; set; }
    public string UpdatedBy { get; set; }
    public Nullable<System.DateTime> UpdatedDatetime { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<FWNotice> FWNotice { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<FWNoticeQueue> FWNoticeQueue { get; set; }
    public virtual ReportDef ReportDef { get; set; }
}

}