namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class FWRefModul
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public FWRefModul()
    {
        this.FWRefModulMenu = new HashSet<FWRefModulMenu>();
    }

    public long ModId { get; set; }
    public Nullable<long> ParentModId { get; set; }
    public string ModKode { get; set; }
    public string ModNama { get; set; }
    public string ModCatatan { get; set; }
    public long ModUrut { get; set; }
    public string ModIconClass { get; set; }
    public Nullable<bool> ModIsPublic { get; set; }
    public Nullable<bool> ModIsHidden { get; set; }
    public string Stsrc { get; set; }
    public string CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDatetime { get; set; }
    public string UpdatedBy { get; set; }
    public Nullable<System.DateTime> UpdatedDatetime { get; set; }
    public string ModTooltip { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<FWRefModulMenu> FWRefModulMenu { get; set; }
}

}