namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class FWRefSetting
{
    public string SetName { get; set; }
    public string SetType { get; set; }
    public string SetValue { get; set; }
    public string SetCatatan { get; set; }
    public string SetGroup { get; set; }
    public bool SetForuser { get; set; }
}

}