namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class FWRoleRight
{
    public long RightId { get; set; }
    public long RoleId { get; set; }
    public long ModId { get; set; }
    public bool IsView { get; set; }
    public bool IsAdd { get; set; }
    public bool IsEdit { get; set; }
    public bool IsDelete { get; set; }
    public bool IsReview { get; set; }
    public bool IsApprove { get; set; }
    public bool IsOpen { get; set; }
    public bool IsPrint { get; set; }
    public bool IsExport { get; set; }
    public string Stsrc { get; set; }
    public string CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDatetime { get; set; }
    public string UpdatedBy { get; set; }
    public Nullable<System.DateTime> UpdatedDatetime { get; set; }

    public virtual FWRoleRight FWRoleRight1 { get; set; }
    public virtual FWRoleRight FWRoleRight2 { get; set; }
}

}