namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Glossary
{
    public long GloId { get; set; }
    public string GloTipe { get; set; }
    public string GloPIdeb { get; set; }
    public string GloDimensi1 { get; set; }
    public string GloDimensi2 { get; set; }
    public string GloKetNilai1 { get; set; }
    public string GloKetNilaiRata2 { get; set; }
    public string stsrc { get; set; }
    public string created_by { get; set; }
    public Nullable<System.DateTime> date_created { get; set; }
    public string modified_by { get; set; }
    public Nullable<System.DateTime> date_modified { get; set; }
}

}