namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class ip_relation_ownership
{
    public System.DateTime dm_periode { get; set; }
    public long rowid { get; set; }
    public Nullable<System.DateTime> dateperiod { get; set; }
    public string sid { get; set; }
    public string nama_sid { get; set; }
    public string securityname { get; set; }
    public Nullable<long> quantity { get; set; }
    public Nullable<decimal> value { get; set; }
    public string rekening_status { get; set; }
    public string accountbalancestatuscode { get; set; }
    public string similaritynote { get; set; }
    public string isdirect { get; set; }
    public string relationshipperiod { get; set; }
    public string relationshipgroup { get; set; }
}

}