namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class ip_relation_sid
{
    public System.DateTime dm_periode { get; set; }
    public long rowid { get; set; }
    public string sid { get; set; }
    public string nama_sid { get; set; }
    public string last_update_sid { get; set; }
    public string trade_id { get; set; }
    public string ktp { get; set; }
    public string npwp { get; set; }
    public string isdirect { get; set; }
    public string noterelationship { get; set; }
    public string suspectnote1 { get; set; }
    public string suspectnote2 { get; set; }
    public string suspectnote3 { get; set; }
    public string relationshipperiod { get; set; }
    public string relationshipgroup { get; set; }
}

}