namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class ip_relation_transaction
{
    public System.DateTime dm_periode { get; set; }
    public long rowid { get; set; }
    public string sid { get; set; }
    public string securityname { get; set; }
    public Nullable<long> buy_quantity { get; set; }
    public Nullable<decimal> buy_value { get; set; }
    public Nullable<int> buy_freq { get; set; }
    public string sell_isdirect { get; set; }
    public string sell_similaritynote { get; set; }
    public string sell_suspectnote { get; set; }
    public string net_suspectnote1 { get; set; }
    public string net_suspectnote2 { get; set; }
    public string net_relationshipperiod { get; set; }
    public string similaritynote { get; set; }
    public string isdirect { get; set; }
    public string relationshipperiod { get; set; }
    public string relationshipgroup { get; set; }
}

}