namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class ip_sid
{
    public System.DateTime dm_periode { get; set; }
    public long rowid { get; set; }
    public string sid { get; set; }
    public string nama_sid { get; set; }
    public string trade_id { get; set; }
    public string ktp { get; set; }
    public string sistem { get; set; }
    public string kitas_skd_number { get; set; }
    public string email { get; set; }
    public string ap4_mobile_phone { get; set; }
    public string tipe_investor_sid { get; set; }
    public string ap4_ktp { get; set; }
    public string address3 { get; set; }
    public string country_of_comp_establishment { get; set; }
    public string ap1_position { get; set; }
    public string last_update_sid { get; set; }
    public string ap4_passport { get; set; }
    public string ap4_email_address { get; set; }
    public string other_fax { get; set; }
    public string ap1_npwp { get; set; }
    public string agama { get; set; }
    public string npwp { get; set; }
    public string ap1_passport { get; set; }
    public string ap2_npwp { get; set; }
    public string nationality { get; set; }
    public string ap4_npwp { get; set; }
    public string nama_ibu_kandung { get; set; }
    public string nationality_sid { get; set; }
    public Nullable<decimal> profit_info_lastyear { get; set; }
    public Nullable<decimal> profit_info_3_years_ago { get; set; }
    public string ap1_middle_name { get; set; }
    public string ap3_last_name { get; set; }
    public string other_mobile_phone { get; set; }
    public string ap4_kitas_skd_number { get; set; }
    public string ap2_kitas_skd_number { get; set; }
    public string legal_domicile { get; set; }
    public string heir_relation { get; set; }
    public string marital_status { get; set; }
    public string ap3_middle_name { get; set; }
    public Nullable<decimal> institutional_income { get; set; }
    public string individual_source_fund { get; set; }
    public string lokal_asing_sid { get; set; }
    public string company_establishment_place { get; set; }
    public string address1 { get; set; }
    public string last_update_rekening { get; set; }
    public Nullable<System.DateTime> tanggal_lahir { get; set; }
    public string other_email { get; set; }
    public string phone_number { get; set; }
    public string passport { get; set; }
    public string other_address1 { get; set; }
    public string ap1_email_address { get; set; }
    public string other_phone_number { get; set; }
    public string ap4_first_name { get; set; }
    public string heir_name { get; set; }
    public string business_registration_number { get; set; }
    public string ap1_first_name { get; set; }
    public string last_name { get; set; }
    public string investment_objective { get; set; }
    public string direct_sid { get; set; }
    public string first_name { get; set; }
    public string ap1_kitas_skd_number { get; set; }
    public string profit_info_2_years_ago { get; set; }
    public Nullable<System.DateTime> dob_sid { get; set; }
    public string other_address2 { get; set; }
    public string city { get; set; }
    public string ap2_first_name { get; set; }
    public string fax { get; set; }
    public string passport_sid { get; set; }
    public string ap2_position { get; set; }
    public string ap2_last_name { get; set; }
    public string province { get; set; }
    public string ap3_email_address { get; set; }
    public string ap2_email_address { get; set; }
    public string asset_info_2_years_ago { get; set; }
    public string middle_name { get; set; }
    public string institutional_source_fund { get; set; }
    public string asset_info_3_years_ago { get; set; }
    public string ap3_kitas_skd_number { get; set; }
    public string birth_place { get; set; }
    public Nullable<System.DateTime> tanggal_pendirian { get; set; }
    public string asset_info_last_year { get; set; }
    public string ap3_npwp { get; set; }
    public string ap1_ktp { get; set; }
    public string ap3_passport { get; set; }
    public string ap4_position { get; set; }
    public string no_rekening { get; set; }
    public string gender { get; set; }
    public string other_province { get; set; }
    public string ap3_first_name { get; set; }
    public string npwp_sid { get; set; }
    public string company_characteristic { get; set; }
    public string nama_rekening { get; set; }
    public string ap3_mobile_phone { get; set; }
    public string ap2_ktp { get; set; }
    public string occupation { get; set; }
    public string ap4_middle_name { get; set; }
    public string ap4_last_name { get; set; }
    public string mobile_phone { get; set; }
    public string other_city { get; set; }
    public string education { get; set; }
    public string address2 { get; set; }
    public string spouse_name { get; set; }
    public string status_sid { get; set; }
    public string ap1_last_name { get; set; }
    public string ap3_ktp { get; set; }
    public string ap2_passport { get; set; }
    public string status_rekening { get; set; }
    public string full_name { get; set; }
    public Nullable<decimal> individual_income { get; set; }
    public string ap1_mobile_phone { get; set; }
    public string kyc_no { get; set; }
    public string ap3_position { get; set; }
    public string ap2_middle_name { get; set; }
    public string id_num_sid { get; set; }
    public string other_address3 { get; set; }
    public string ap2_mobile_phone { get; set; }
    public string postal_code { get; set; }
    public string country { get; set; }
    public string kode_member { get; set; }
    public string nama_member { get; set; }
    public string valid_from { get; set; }
    public string valid_until { get; set; }
    public string is_active { get; set; }
}

}