namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class ip_transaction
{
    public System.DateTime dm_periode { get; set; }
    public long rowid { get; set; }
    public string sid { get; set; }
    public string nama_sid { get; set; }
    public string trade_id { get; set; }
    public string ktp { get; set; }
    public string npwp { get; set; }
    public string securitycode { get; set; }
    public string securityname { get; set; }
    public Nullable<decimal> buy_value { get; set; }
    public Nullable<long> buy_quantity { get; set; }
    public Nullable<int> buy_freq { get; set; }
    public Nullable<decimal> sell_value { get; set; }
    public Nullable<long> sell_quantity { get; set; }
    public Nullable<int> sell_freq { get; set; }
    public Nullable<decimal> net_value { get; set; }
    public Nullable<long> net_quantity { get; set; }
    public Nullable<int> net_freq { get; set; }
    public string system { get; set; }
    public string periode { get; set; }
}

}