namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class la_inquiry_pattern_recognition
{
    public long rowid { get; set; }
    public System.DateTime dm_periode { get; set; }
    public string dm_jenis_ljk { get; set; }
    public string dm_kode_ljk { get; set; }
    public string dm_jenis_debitur { get; set; }
    public string dm_cif { get; set; }
    public string dm_nama_debitur { get; set; }
    public string dm_nomor_rekening { get; set; }
    public string dm_no_id_debitur { get; set; }
    public Nullable<System.DateTime> dm_tanggal_lahir { get; set; }
    public string dm_tempat_lahir { get; set; }
    public string dm_kode_gender { get; set; }
    public string dm_jenis_kredit { get; set; }
    public string dm_jenis_penggunaan { get; set; }
    public string dm_sifat_kredit { get; set; }
    public string dm_no_akad_akhir { get; set; }
    public Nullable<decimal> dm_nilai_outstanding { get; set; }
    public Nullable<decimal> dm_nilai_plafon { get; set; }
    public Nullable<decimal> dm_nilai_baki_debet { get; set; }
    public string dm_jenis_fasilitas_pinjaman { get; set; }
    public Nullable<System.DateTime> dm_tanggal_awal_pinjaman { get; set; }
    public Nullable<System.DateTime> dm_tanggal_inquiry { get; set; }
    public Nullable<decimal> dm_selisih_awalvsinquiry { get; set; }
    public string dm_status_pengecekan { get; set; }
    public string dm_periode_inquiry { get; set; }
    public string dm_inquiry_id { get; set; }
    public string dm_algoritma_pencarian { get; set; }
    public string dm_created_by { get; set; }
    public string dm_nomor_laporan_inquiry { get; set; }
    public string dm_kode_kantor_cabang { get; set; }
    public string dm_nama_kantor_cabang { get; set; }
    public string dm_status_inquiry { get; set; }
    public string dm_cek_sebelum_pencairan { get; set; }
    public string dm_cek_setelah_pencairan { get; set; }
    public string dm_cek_1bulan_sebelum_cair { get; set; }
    public string dm_cek_1bulan_setelah_cair { get; set; }
    public Nullable<int> dm_pperiode_inquiry { get; set; }
    public string dm_pstatus_pengecekan { get; set; }
}

}