namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Log_ETL
{
    public long log_id { get; set; }
    public System.DateTime log_date { get; set; }
    public string log_tipe { get; set; }
    public string log_periode { get; set; }
    public Nullable<long> log_delete_cnt { get; set; }
    public Nullable<long> log_insert_cnt { get; set; }
    public Nullable<System.DateTime> log_start { get; set; }
    public Nullable<System.DateTime> log_end { get; set; }
    public string log_status { get; set; }
    public string log_errmessage { get; set; }
}

}