namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class log_monitoring_bda_slik_det
{
    public long row_id { get; set; }
    public string segmentasi { get; set; }
    public System.DateTime bulan_laporan { get; set; }
    public Nullable<System.DateTime> tanggal_cetak { get; set; }
    public Nullable<System.DateTime> tanggal_terima { get; set; }
    public Nullable<decimal> selisih_waktu { get; set; }
    public Nullable<System.DateTime> pyearmonth { get; set; }
}

}