namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class log_monitoring_bda_slik_sum
{
    public long row_id { get; set; }
    public string segmentasi { get; set; }
    public System.DateTime bulan_laporan { get; set; }
    public string kode_kondisi { get; set; }
    public Nullable<decimal> total_account { get; set; }
    public Nullable<decimal> baki_debet { get; set; }
    public string pfeed { get; set; }
    public Nullable<System.DateTime> pyearmonth { get; set; }
}

}