namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class LOG_AKSES
{
    public long log_id { get; set; }
    public string RemoteHost { get; set; }
    public string AuthUser { get; set; }
    public Nullable<System.DateTime> StartDate { get; set; }
    public string RequestLine { get; set; }
    public string StatusCode { get; set; }
}

}