namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class ma_aml_cft_analysis
{
    public System.DateTime dm_periode { get; set; }
    public long rowid { get; set; }
    public string dm_jenis_ljk { get; set; }
    public string dm_kode_ljk { get; set; }
    public string dm_cif { get; set; }
    public string dm_nama_debitur { get; set; }
    public string dm_nomor_rekening { get; set; }
    public string dm_kode_credit_nature { get; set; }
    public string dm_kode_jenis_pinjaman { get; set; }
    public string dm_kode_skema_pinjaman { get; set; }
    public string dm_jenis_agunan { get; set; }
    public Nullable<decimal> dm_agunan { get; set; }
    public Nullable<decimal> dm_plafon { get; set; }
    public Nullable<decimal> dm_outstanding { get; set; }
    public Nullable<decimal> dm_baki_debet { get; set; }
    public string dm_kolektibilitas { get; set; }
}

}