namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class ma_analisis_pencurian_identitas
{
    public System.DateTime dm_periode { get; set; }
    public long rowid { get; set; }
    public string dm_jenis_ljk { get; set; }
    public string dm_kode_ljk { get; set; }
    public string dm_cif { get; set; }
    public string dm_no_rekening { get; set; }
    public string dm_nama_debitur { get; set; }
    public string dm_kode_jenis_id_debitur { get; set; }
    public string dm_no_id_debitur { get; set; }
    public string dm_nama_id_debitur { get; set; }
    public string dm_nama_ibu_kandung { get; set; }
    public Nullable<System.DateTime> dm_tanggal_lahir { get; set; }
    public string dm_status_id_debitur_valid { get; set; }
    public string dm_nama_id_debitur_2 { get; set; }
    public Nullable<double> dm_similarity_score { get; set; }
    public Nullable<int> dm_similarity_result { get; set; }
    public string dm_kategori_asesmen { get; set; }
}

}