namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class ma_anomali_plafon_by_pekerjaan_debitur
{
    public System.DateTime dm_periode { get; set; }
    public long rowid { get; set; }
    public string dm_jenis_ljk { get; set; }
    public string dm_kode_ljk { get; set; }
    public string dm_kode_jenis_pinjaman { get; set; }
    public string dm_jenis_penggunaan { get; set; }
    public string dm_cif { get; set; }
    public string dm_no_rekening { get; set; }
    public string dm_nama_debitur { get; set; }
    public decimal dm_outstanding { get; set; }
    public decimal dm_baki_debet { get; set; }
    public decimal dm_plafon { get; set; }
    public Nullable<decimal> dm_avg_plafon { get; set; }
    public string dm_status_plafon { get; set; }
    public string dm_kode_profesi_debitur { get; set; }
    public string dm_profesi_debitur { get; set; }
    public Nullable<System.DateTime> dm_tanggal_kontrak { get; set; }
    public Nullable<System.DateTime> dm_tanggal_jatuh_tempo { get; set; }
    public string dm_kondisi { get; set; }
    public Nullable<decimal> dm_plafon_above_threshold { get; set; }
    public Nullable<decimal> dm_plafon_below_threshold { get; set; }
}

}