namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class ma_outstanding_macet_no_agunan
{
    public System.DateTime dm_periode { get; set; }
    public long rowid { get; set; }
    public string dm_jenis_ljk { get; set; }
    public string dm_kode_ljk { get; set; }
    public string dm_cif { get; set; }
    public string dm_nomor_rekening { get; set; }
    public string dm_nama_debitur { get; set; }
    public string dm_jenis_kredit { get; set; }
    public string dm_jenis_penggunaan { get; set; }
    public string dm_kolektibilitas { get; set; }
    public Nullable<decimal> dm_nominal_kredit { get; set; }
    public Nullable<decimal> dm_plafon { get; set; }
    public Nullable<System.DateTime> dm_tanggal_kontrak { get; set; }
    public Nullable<System.DateTime> dm_tanggal_jatuh_tempo { get; set; }
    public string dm_lokasi_agunan { get; set; }
    public string dm_jenis_agunan { get; set; }
    public Nullable<decimal> dm_baki_debet_avg { get; set; }
    public Nullable<decimal> dm_baki_debet_above_threshold { get; set; }
    public Nullable<decimal> dm_baki_debet_below_threshold { get; set; }
    public string dm_baki_debet_status { get; set; }
}

}