namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class ma_rekening_baru_non_restrukturisasi_npl
{
    public System.DateTime dm_periode { get; set; }
    public long rowid { get; set; }
    public string dm_jenis_ljk { get; set; }
    public string dm_kode_ljk { get; set; }
    public string dm_kode_jenis_pinjaman { get; set; }
    public string dm_cif { get; set; }
    public string dm_no_rekening { get; set; }
    public string dm_nama_debitur { get; set; }
    public Nullable<decimal> dm_outstanding { get; set; }
    public Nullable<decimal> dm_baki_debet { get; set; }
    public Nullable<decimal> dm_plafon { get; set; }
    public Nullable<int> dm_jumlah_hari_tunggakan { get; set; }
    public Nullable<int> dm_npl { get; set; }
    public Nullable<System.DateTime> dm_tanggal_mulai { get; set; }
    public Nullable<System.DateTime> dm_tanggal_awal_pinjaman { get; set; }
    public Nullable<System.DateTime> dm_tanggal_jatuh_tempo { get; set; }
    public Nullable<int> dm_selisih_awalvsperiode { get; set; }
}

}