namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class macro_pertumbuhan_pinjaman_level_ljk
{
    public System.DateTime dm_periode { get; set; }
    public long rowid { get; set; }
    public string dm_jenis_ljk { get; set; }
    public string dm_kode_ljk { get; set; }
    public Nullable<decimal> dm_outstanding_sekarang { get; set; }
    public Nullable<decimal> dm_outstanding_sebelumnya { get; set; }
    public Nullable<decimal> dm_persen_pertumbuhan_outstanding { get; set; }
    public string dm_jenis_pertumbuhan { get; set; }
    public string dm_current_period { get; set; }
    public string dm_prev_period { get; set; }
}

}