namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class macro_output_forecast_level_ljk
{
    public System.DateTime dm_periode { get; set; }
    public long rowid { get; set; }
    public string dm_fasilitas_pinjaman { get; set; }
    public string dm_jenis_ljk { get; set; }
    public string dm_kode_ljk { get; set; }
    public string dm_tipe_forecasting { get; set; }
    public Nullable<decimal> dm_nilai { get; set; }
    public string dm_status { get; set; }
    public Nullable<System.DateTime> dm_date_generated { get; set; }
    public Nullable<System.DateTime> dm_pperiode { get; set; }
}

}