namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class macro_penetrasi_lending_ljk
{
    public System.DateTime dm_periode { get; set; }
    public long rowid { get; set; }
    public string dm_jenis_ljk { get; set; }
    public string dm_kode_ljk { get; set; }
    public string dm_fasilitas_pinjaman { get; set; }
    public string dm_jenis_debitur { get; set; }
    public string dm_kategori { get; set; }
    public string dm_deskripsi_kategori { get; set; }
    public Nullable<int> dm_jumlah_cif { get; set; }
    public Nullable<int> dm_jumlah_rekening { get; set; }
    public Nullable<int> dm_jumlah_rekening_nonzero_os { get; set; }
    public Nullable<decimal> dm_plafon_awal { get; set; }
    public Nullable<decimal> dm_avg_plafon_awal { get; set; }
    public Nullable<decimal> dm_plafon_efektif { get; set; }
    public Nullable<decimal> dm_avg_plafon_efektif { get; set; }
    public Nullable<decimal> dm_outstanding { get; set; }
    public Nullable<decimal> dm_avg_outstanding { get; set; }
}

}