namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class market_driven_stp_clearing
{
    public int clearingdatesk { get; set; }
    public int settlementdatesk { get; set; }
    public string investorid { get; set; }
    public string securitycode { get; set; }
    public string securitycompanycode { get; set; }
    public string clearingobligationquantity { get; set; }
    public int periode { get; set; }
}

}