namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class market_driven_ape_growth1
{
    public string history_type { get; set; }
    public int periode_lvl0 { get; set; }
    public int periode_lvl1 { get; set; }
    public int periode_lvl2 { get; set; }
    public string security_code { get; set; }
    public string security_name { get; set; }
    public string volume { get; set; }
    public string value { get; set; }
    public double freq { get; set; }
    public string turnover { get; set; }
    public string weight { get; set; }
    public string lowvalue { get; set; }
    public string highvalue { get; set; }
    public string price { get; set; }
    public string listedshares { get; set; }
    public string bmc { get; set; }
    public string changeprice { get; set; }
    public string mc { get; set; }
    public string point { get; set; }
    public string ranking_point { get; set; }
    public string ranking_changeprice { get; set; }
    public string net_volume { get; set; }
    public string net_value { get; set; }
    public string flag_volume { get; set; }
    public string flag_value { get; set; }
    public int periode { get; set; }
}

}