namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class market_driven_rg_ng1
{
    public string history_type { get; set; }
    public int periode_lvl1 { get; set; }
    public int periode_lvl2 { get; set; }
    public int periode_lvl3 { get; set; }
    public string security_code { get; set; }
    public string market { get; set; }
    public string volume { get; set; }
    public string value { get; set; }
    public long freq { get; set; }
    public string low { get; set; }
    public string high { get; set; }
    public string close { get; set; }
    public int periode { get; set; }
}

}