namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class market_driven_validasi_data_tra
{
    public int tradeno { get; set; }
    public int tradedatesk { get; set; }
    public System.DateTime tradingdatetime { get; set; }
    public int tradinghourcode { get; set; }
    public string tradingminutecode { get; set; }
    public string securitycode { get; set; }
    public string transactiontypecode { get; set; }
    public string exchangemembercode { get; set; }
    public int investorcode { get; set; }
    public string investororigincode { get; set; }
    public string cpemcode { get; set; }
    public string cpinvestorcode { get; set; }
    public int quantity { get; set; }
    public string listingboardcode { get; set; }
    public int value { get; set; }
    public string transactionboardcode { get; set; }
    public string sid { get; set; }
    public string lokal_asing_sid { get; set; }
    public string countryinvestor { get; set; }
    public string provinceinvestor { get; set; }
    public string typeinvestor { get; set; }
    public string countrycpinvestor { get; set; }
    public string provincecpinvestor { get; set; }
    public string typecpinvestor { get; set; }
    public System.DateTime flag_minute { get; set; }
    public bool confirmation { get; set; }
    public string sid_name { get; set; }
    public int periode { get; set; }
}

}