namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class market_driven_sum_trades
{
    public int calendarsk { get; set; }
    public double closingvalue { get; set; }
    public double tradingvolume { get; set; }
    public double tradingvalue { get; set; }
    public double marketcapitalizationamount { get; set; }
    public double value_buy { get; set; }
    public double value_sell { get; set; }
    public double net_value { get; set; }
    public string flag_value { get; set; }
    public double volume_buy { get; set; }
    public double volume_sell { get; set; }
    public double net_volume { get; set; }
    public string flag_volume { get; set; }
    public int periode { get; set; }
}

}