namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class market_driven_stp_balance1
{
    public int tanggal_balance { get; set; }
    public string sid { get; set; }
    public string trading_id { get; set; }
    public string efek { get; set; }
    public string subrekening_efek { get; set; }
    public double quantity { get; set; }
    public double price { get; set; }
    public int periode { get; set; }
}

}