namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class market_driven_stp_tra
{
    public int settledate { get; set; }
    public int tradedatesk { get; set; }
    public string sid { get; set; }
    public int investorcode { get; set; }
    public string securitycode { get; set; }
    public string transactiontypecode { get; set; }
    public double volume { get; set; }
    public string cpinvestorcode { get; set; }
    public int periode { get; set; }
}

}