namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class MEMBERS
{
    public string Kode_Jenis_LJK { get; set; }
    public string Kode_LJK { get; set; }
    public string Nama_LJK { get; set; }
    public string Nama_Penanggung_Jawab_LJK { get; set; }
    public string Nomor_Telp_Penanggung_Jawab { get; set; }
    public string Alamat_Email_Penanggung_Jawab { get; set; }
    public string Kode_Kab_Kota_DATI_II { get; set; }
    public string Kecamatan { get; set; }
    public string Kelurahan { get; set; }
    public string Alamat { get; set; }
    public string Alamat_Website { get; set; }
    public string Tahun_bulan_data_Terakhir { get; set; }
    public string Status_Submission_Inisial { get; set; }
    public string Kode_Kantor_Cabang { get; set; }
    public string Status_Aktif { get; set; }
    public string Status_Delete { get; set; }
    public string Create_Date { get; set; }
    public string Update_Date { get; set; }
}

}