namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class ml_log_mon_data
{
    public System.DateTime dm_periode { get; set; }
    public long rowid { get; set; }
    public string kode_job { get; set; }
    public string nama_job { get; set; }
    public Nullable<int> urutan_proses { get; set; }
    public Nullable<byte> status { get; set; }
    public Nullable<decimal> persentase { get; set; }
    public Nullable<System.DateTime> periode_data { get; set; }
    public Nullable<System.DateTime> waktu_mulai { get; set; }
    public Nullable<System.DateTime> waktu_selesai { get; set; }
    public Nullable<int> total_insert { get; set; }
    public Nullable<int> total_delete { get; set; }
    public string keterangan { get; set; }
}

}