namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class mm_spv
{
    public System.DateTime dm_periode { get; set; }
    public long rowid { get; set; }
    public string sid { get; set; }
    public string nama_sid { get; set; }
    public string trade_id { get; set; }
    public string seller { get; set; }
    public string buyer { get; set; }
    public Nullable<long> volume { get; set; }
    public Nullable<decimal> value { get; set; }
    public Nullable<decimal> price { get; set; }
    public Nullable<System.DateTime> trade_date { get; set; }
    public Nullable<System.DateTime> trade_time { get; set; }
    public string set_data { get; set; }
    public string note { get; set; }
    public string isAlert { get; set; }
    public string isSettled { get; set; }
    public string isComply { get; set; }
}

}