namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class ms_pinjaman_baru_bersamaan_sum
{
    public string dm_kode_ljk_filter { get; set; }
    public System.DateTime dm_periode { get; set; }
    public long rowid { get; set; }
    public Nullable<int> dm_total_account { get; set; }
    public Nullable<decimal> dm_total_plafon { get; set; }
    public Nullable<decimal> dm_total_outstanding { get; set; }
    public string dm_list_ljk { get; set; }
    public string dm_jenis_ljk { get; set; }
    public string dm_kolektibilitas { get; set; }
}

}