namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class ms_pinjaman_baru_bersamaan_det
{
    public string dm_kode_ljk_filter { get; set; }
    public System.DateTime dm_periode { get; set; }
    public long rowid { get; set; }
    public string dm_jenis_ljk { get; set; }
    public string dm_jenis_ljk_filter { get; set; }
    public string dm_kode_ljk { get; set; }
    public string dm_jenis_debitur { get; set; }
    public string dm_cif { get; set; }
    public string dm_no_rekening { get; set; }
    public string dm_no_id_debitur { get; set; }
    public string dm_nama_debitur { get; set; }
    public Nullable<decimal> dm_outstanding { get; set; }
    public Nullable<decimal> dm_plafon { get; set; }
    public Nullable<decimal> dm_baki_debet { get; set; }
    public string dm_jenis_fasilitas_pinjaman { get; set; }
    public string dm_kolektibilitas { get; set; }
    public Nullable<System.DateTime> dm_tanggal_akad_awal { get; set; }
    public Nullable<System.DateTime> dm_tanggal_awal_pinjaman { get; set; }
    public Nullable<System.DateTime> dm_tanggal_awal_pinjaman_m1 { get; set; }
    public Nullable<double> dm_selisih_bulan { get; set; }
    public Nullable<decimal> dm_denda { get; set; }
    public Nullable<decimal> dm_tunggakan_pokok { get; set; }
    public Nullable<decimal> dm_tunggakan_bunga { get; set; }
    public string member_type_code { get; set; }
    public string member_code { get; set; }
}

}