namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class ms_pemberian_pinjaman_karyawan_ljk
{
    public System.DateTime dm_periode { get; set; }
    public long rowid { get; set; }
    public string dm_jenis_ljk { get; set; }
    public string dm_kode_ljk { get; set; }
    public string dm_jenis_debitur { get; set; }
    public string dm_cif { get; set; }
    public string dm_nama_debitur { get; set; }
    public string dm_no_rekening { get; set; }
    public string dm_kode_jenis_pinjaman { get; set; }
    public Nullable<decimal> dm_outstanding { get; set; }
    public Nullable<decimal> dm_avg_outstanding_market { get; set; }
    public Nullable<decimal> dm_plafon { get; set; }
    public Nullable<decimal> dm_avg_plafon_market { get; set; }
    public Nullable<decimal> dm_baki_debet { get; set; }
    public Nullable<decimal> dm_avg_baki_debet_market { get; set; }
    public Nullable<decimal> dm_suku_bunga { get; set; }
    public Nullable<decimal> dm_avg_suku_bunga { get; set; }
    public Nullable<decimal> dm_above_threshold_plafon_market { get; set; }
    public Nullable<decimal> dm_below_threshold_plafon_market { get; set; }
    public string dm_status_plafon { get; set; }
    public Nullable<decimal> dm_above_threshold_baki_debet_market { get; set; }
    public Nullable<decimal> dm_below_threshold_baki_debet_market { get; set; }
    public string dm_status_baki_debet { get; set; }
    public string dm_pekerjaan { get; set; }
    public string dm_tempat_bekerja { get; set; }
    public string dm_bidang_usaha { get; set; }
}

}