namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class ms_perubahan_suku_bunga_no_restrukturisasi
{
    public System.DateTime dm_periode { get; set; }
    public long rowid { get; set; }
    public string dm_jenis_ljk { get; set; }
    public string dm_kode_ljk { get; set; }
    public string dm_jenis_debitur { get; set; }
    public string dm_cif { get; set; }
    public string dm_no_rekening { get; set; }
    public string dm_nama_debitur { get; set; }
    public string dm_kode_jenis_pinjaman { get; set; }
    public string dm_kolektibilitas { get; set; }
    public string dm_sektor_ekonomi { get; set; }
    public string dm_jenis_suku_bunga { get; set; }
    public Nullable<decimal> dm_suku_bunga_sekarang { get; set; }
    public Nullable<decimal> dm_suku_bunga_sebelumnya { get; set; }
    public Nullable<decimal> dm_perubahan_suku_bunga { get; set; }
    public string dm_status_threshold_suku_bunga { get; set; }
}

}