namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class node_collateral
{
    public System.DateTime dm_periode { get; set; }
    public long rowid { get; set; }
    public string dm_node_id { get; set; }
    public string dm_node_type { get; set; }
    public string dm_node_subtype { get; set; }
    public Nullable<int> dm_number_of_credit_facility_type { get; set; }
    public string dm_has_joint_credit { get; set; }
    public Nullable<long> dm_number_of_ljk { get; set; }
    public Nullable<long> dm_number_of_cif { get; set; }
    public Nullable<long> dm_number_of_credit_acc { get; set; }
    public Nullable<long> dm_number_of_active_credit_acc { get; set; }
    public string dm_value_from { get; set; }
    public Nullable<decimal> dm_value { get; set; }
    public Nullable<double> dm_node_size_factor { get; set; }
    public string dm_node_color_type { get; set; }
}

}