namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class osida_pengurus_pemilik_kredit_bermasalah_mst
{
    public System.DateTime dm_periode { get; set; }
    public long rowid { get; set; }
    public string dm_jenis_ljk { get; set; }
    public string dm_kode_ljk { get; set; }
    public string dm_nama_ljk { get; set; }
    public string dm_cif { get; set; }
    public string dm_nama_nasabah { get; set; }
    public string dm_kualitas { get; set; }
    public Nullable<decimal> dm_total_plafon { get; set; }
    public Nullable<decimal> dm_total_baki_debet { get; set; }
    public string dm_nama_pengurus_pemilik { get; set; }
    public string dm_kode_kantor_cabang { get; set; }
    public string dm_jabatan { get; set; }
    public Nullable<decimal> dm_pangsa_pemilik { get; set; }
    public Nullable<decimal> dm_total_baki_debet_bermasalah { get; set; }
    public Nullable<decimal> dm_total_tunggakan_bunga { get; set; }
    public string dm_nama_kantor_cabang { get; set; }
}

}