namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class osida_hapusbuku_satu_tahun
{
    public System.DateTime dm_periode { get; set; }
    public long rowid { get; set; }
    public string dm_jenis_ljk { get; set; }
    public string dm_kode_ljk { get; set; }
    public string dm_no_rekening { get; set; }
    public string dm_cif { get; set; }
    public string dm_nama_debitur { get; set; }
    public string dm_jenis_kredit { get; set; }
    public string dm_jenis_penggunaan { get; set; }
    public string dm_sifat_kredit { get; set; }
    public System.DateTime dm_tanggal_akad_akhir { get; set; }
    public Nullable<double> dm_jumlah_bulan_dari_akad_akhir { get; set; }
    public System.DateTime dm_tanggal_awal_pinjaman { get; set; }
    public System.DateTime dm_tanggal_mulai { get; set; }
    public System.DateTime dm_tanggal_jatuh_tempo { get; set; }
    public string dm_baru_perpanjangan { get; set; }
    public string dm_valuta { get; set; }
    public Nullable<decimal> dm_plafon_awal { get; set; }
    public Nullable<decimal> dm_plafon { get; set; }
    public Nullable<decimal> dm_baki_debet { get; set; }
    public string dm_kolektibilitas { get; set; }
    public Nullable<int> dm_jumlah_hari_tunggakan { get; set; }
    public Nullable<decimal> dm_tunggakan_pokok { get; set; }
    public Nullable<decimal> dm_tunggakan_bunga { get; set; }
    public Nullable<decimal> dm_denda { get; set; }
    public string dm_kondisi { get; set; }
    public Nullable<System.DateTime> dm_tanggal_kondisi { get; set; }
    public string dm_kode_kantor_cabang { get; set; }
    public string dm_nama_kantor_cabang { get; set; }
    public string dm_no_akad_akhir { get; set; }
}

}