namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class osida_kredit_macet_tdk_hb_det
{
    public System.DateTime dm_periode { get; set; }
    public long rowid { get; set; }
    public string dm_jenis_ljk { get; set; }
    public string dm_kode_ljk { get; set; }
    public string dm_kode_kantor_cabang { get; set; }
    public string dm_nama_ljk { get; set; }
    public string dm_nama_kantor_cabang { get; set; }
    public string dm_cif { get; set; }
    public string dm_no_rekening { get; set; }
    public string dm_nama_nasabah { get; set; }
    public string dm_no_agunan { get; set; }
    public string dm_jenis_agunan { get; set; }
    public string dm_jenis_ikat { get; set; }
    public string dm_nama_pemilik_agunan { get; set; }
    public string dm_bukti_kepemilikan { get; set; }
    public string dm_alamat_agunan { get; set; }
    public string dm_lokasi_agunan { get; set; }
    public Nullable<decimal> dm_nilai_agunan_njop { get; set; }
    public Nullable<decimal> dm_nilai_agunan_ljk { get; set; }
    public Nullable<decimal> dm_nilai_agunan_penilai_independen { get; set; }
}

}