namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class osida_plafondering_umum_master
{
    public long rowid { get; set; }
    public System.DateTime dm_periode { get; set; }
    public string dm_jenis_ljk { get; set; }
    public string dm_kode_ljk { get; set; }
    public string dm_cif { get; set; }
    public string dm_nama_debitur { get; set; }
    public Nullable<int> dm_jumlah_rekeninglunas_bulanlau { get; set; }
    public Nullable<decimal> dm_plafonawal_bulanlalu { get; set; }
    public Nullable<decimal> dm_bakidebet_bulanlalu { get; set; }
    public Nullable<decimal> dm_tunggakanbunga_bulanlalu { get; set; }
    public Nullable<decimal> dm_jumlah_rekeningbaru_bulanpelaporan { get; set; }
    public Nullable<decimal> dm_plafonawal_bulanpelaporan { get; set; }
    public Nullable<decimal> dm_bakidebet_bulanpelaporan { get; set; }
    public Nullable<decimal> dm_tunggakanbunga_bulanpelaporan { get; set; }
    public Nullable<decimal> dm_jumlah_plafon_rekening_baru { get; set; }
    public string dm_id_filter { get; set; }
}

}