namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class osida_alih_deb_ke_bank_mst
{
    public System.DateTime dm_periode { get; set; }
    public long rowid { get; set; }
    public string dm_jenis_ljk { get; set; }
    public string dm_kode_ljk { get; set; }
    public string dm_kode_kantor_cabang { get; set; }
    public string dm_nama_ljk { get; set; }
    public string dm_nama_kantor_cabang { get; set; }
    public string dm_cif { get; set; }
    public string dm_nama_id_debitur { get; set; }
    public string dm_no_rekening { get; set; }
    public Nullable<decimal> dm_total_plafon_awal { get; set; }
    public Nullable<decimal> dm_total_baki_debet { get; set; }
    public Nullable<decimal> dm_tunggakan { get; set; }
    public Nullable<decimal> dm_jml_rekening_baru { get; set; }
    public Nullable<decimal> dm_plafon_awal { get; set; }
    public Nullable<decimal> dm_baki_debet { get; set; }
}

}