namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class osida_info_keu_tdk_update_mst
{
    public System.DateTime dm_periode { get; set; }
    public long rowid { get; set; }
    public string dm_jenis_ljk { get; set; }
    public string dm_kode_ljk { get; set; }
    public string dm_kode_kantor_cabang { get; set; }
    public string dm_nama_ljk { get; set; }
    public string dm_nama_kantor_cabang { get; set; }
    public string dm_cif { get; set; }
    public string dm_nama_id_debitur { get; set; }
    public string dm_no_rekening { get; set; }
    public Nullable<decimal> dm_total_plafon { get; set; }
    public Nullable<decimal> dm_total_baki_debet { get; set; }
    public string dm_posisi_laporan_keuangan_terakhir { get; set; }
    public string dm_kualitas_terburuk { get; set; }
}

}