namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class osida_pemberian_kur_deb_noneligible_mst
{
    public System.DateTime dm_periode { get; set; }
    public long rowid { get; set; }
    public string dm_jenis_ljk { get; set; }
    public string dm_kode_ljk { get; set; }
    public string dm_nama_ljk { get; set; }
    public string dm_cif { get; set; }
    public string dm_nama_nasabah { get; set; }
    public string dm_kode_kantor_cabang { get; set; }
    public string dm_nik { get; set; }
    public Nullable<decimal> dm_jml_rek_fasilitas_kredit_baru { get; set; }
    public Nullable<decimal> dm_plafon_kredit_baru { get; set; }
    public Nullable<decimal> dm_baki_debet_kredit_baru { get; set; }
    public string dm_nama_kantor_cabang { get; set; }
    public Nullable<decimal> dm_jml_rekening { get; set; }
    public Nullable<decimal> dm_baki_debet_bulan_lalu { get; set; }
    public Nullable<decimal> dm_tunggakan_bunga_bulan_lalu { get; set; }
}

}