namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class osint_scrapping_filtered
{
    public long rowid { get; set; }
    public System.DateTime dm_pperiode_scrapping { get; set; }
    public Nullable<System.DateTime> dm_scrapping_time { get; set; }
    public string dm_keyword { get; set; }
    public string dm_judul_berita { get; set; }
    public string dm_url { get; set; }
    public string dm_snippet { get; set; }
    public string dm_text { get; set; }
    public string dm_clean_text { get; set; }
    public string dm_pday_scrapping { get; set; }
    public string dm_pcategory_scrapping { get; set; }
}

}