namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class osint_tfidf_wordcloud
{
    public long rowid { get; set; }
    public System.DateTime dm_pperiode_scrapping { get; set; }
    public string dm_key_word { get; set; }
    public string dm_token { get; set; }
    public string dm_score { get; set; }
    public Nullable<int> dm_freq { get; set; }
    public Nullable<int> dm_pday_scrapping { get; set; }
    public string dm_pcategory_scrapping { get; set; }
}

}