namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class pe_segmentation_det_reksa_dana
{
    public System.DateTime calendardate { get; set; }
    public Nullable<int> securitycompanysk { get; set; }
    public string securitycompanycode { get; set; }
    public string securitycompanyname { get; set; }
    public Nullable<int> mutualfundtypesk { get; set; }
    public string mutualfundtypecode { get; set; }
    public string mutualfundtypename { get; set; }
    public string mutualfundname { get; set; }
    public string isaffiliated { get; set; }
    public Nullable<double> netassetvalueunit { get; set; }
    public Nullable<double> netassetvaluemutualfund { get; set; }
    public string liabilitiesrankingcal { get; set; }
    public Nullable<double> mkbdlimitationvalue { get; set; }
    public Nullable<double> mkbdlimitationexcessvalue { get; set; }
    public string periode { get; set; }
}

}