//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDA.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class pe_segmentation_sum_cluster_mkbd
    {
        public long rowid { get; set; }
        public System.DateTime calendardate { get; set; }
        public Nullable<int> securitycompanysk { get; set; }
        public string securitycompanycode { get; set; }
        public string securitycompanyname { get; set; }
        public Nullable<double> simpanangiro { get; set; }
        public Nullable<double> depositolt3bulan { get; set; }
        public Nullable<double> depositogt3bulandijaminlps { get; set; }
        public Nullable<double> uangjaminanlkp { get; set; }
        public Nullable<double> kasdansetarakas { get; set; }
        public Nullable<double> mkbd { get; set; }
        public Nullable<double> mkbdminimum { get; set; }
        public Nullable<double> mkbdpermkbdminimum { get; set; }
        public string cluster { get; set; }
        public System.DateTime periode { get; set; }
    }
}
