//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDA.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class pe_segmentation_det_portofolio_saham
    {
        public long rowid { get; set; }
        public System.DateTime calendardate { get; set; }
        public Nullable<int> securitycompanysk { get; set; }
        public string securitycompanycode { get; set; }
        public string securitycompanyname { get; set; }
        public Nullable<int> securitysk { get; set; }
        public string securitycode { get; set; }
        public string securitytypename { get; set; }
        public string affiliated { get; set; }
        public Nullable<double> nominalsheet { get; set; }
        public Nullable<double> acquisitionprice { get; set; }
        public Nullable<double> fairmarketprice { get; set; }
        public Nullable<double> fairmarketvalue { get; set; }
        public Nullable<double> gainperloss { get; set; }
        public Nullable<double> fairmarketvaluepertotalporto { get; set; }
        public string entitygroup { get; set; }
        public string marketvaluepercentage { get; set; }
        public Nullable<double> liabilitiesrankingvalue { get; set; }
        public System.DateTime periode { get; set; }
    }
}
