namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class pe_segmentation_det_jaminan_margin
{
    public System.DateTime calendardate { get; set; }
    public Nullable<int> securitycompanysk { get; set; }
    public string securitycompanycode { get; set; }
    public string securitycompanyname { get; set; }
    public Nullable<int> securitysk { get; set; }
    public string securitycode { get; set; }
    public string securityname { get; set; }
    public Nullable<int> volume { get; set; }
    public Nullable<int> price { get; set; }
    public Nullable<long> fairmarketvalue { get; set; }
    public string periode { get; set; }
}

}