namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class pe_segmentation_hutang_subordinasi_det
{
    public System.DateTime dm_periode { get; set; }
    public long rowid { get; set; }
    public Nullable<System.DateTime> calendardate { get; set; }
    public Nullable<int> securitycompanysk { get; set; }
    public string securitycompanycode { get; set; }
    public string securitycompanyname { get; set; }
    public Nullable<decimal> mkbdaccountbalance { get; set; }
    public Nullable<System.DateTime> buyingdate { get; set; }
    public Nullable<decimal> buyingamount { get; set; }
    public string sellername { get; set; }
    public Nullable<decimal> rr_per_hso { get; set; }
    public string periode { get; set; }
}

}