namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class pe_segmentation_pembiayaan_vs_jaminan_saham
{
    public System.DateTime dm_periode { get; set; }
    public long rowid { get; set; }
    public Nullable<System.DateTime> calendardate { get; set; }
    public Nullable<int> securitycompanysk { get; set; }
    public string securitycompanycode { get; set; }
    public string securitycompanyname { get; set; }
    public string kodeefek { get; set; }
    public Nullable<int> volume { get; set; }
    public Nullable<decimal> value { get; set; }
    public string groupemiten { get; set; }
    public Nullable<int> flag { get; set; }
    public string periode { get; set; }
}

}