namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class pengawas_ljk
{
    public string user_login_id { get; set; }
    public string orgn_name { get; set; }
    public string employee_id { get; set; }
    public string phone_number { get; set; }
    public string group_name { get; set; }
    public string active_flag { get; set; }
    public string member_type_code { get; set; }
    public string member_code { get; set; }
    public string created_datetime { get; set; }
    public string created_by { get; set; }
    public string updated_datetime { get; set; }
    public string updated_by { get; set; }
    public string p_date { get; set; }
    public Nullable<System.DateTime> sync_date { get; set; }
}

}