namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class ref_credit_types
{
    public long rowid { get; set; }
    public string dm_kode_jenis_kredit_pembiayaan { get; set; }
    public string dm_deskripsi_jenis_kredit_pembiayaan { get; set; }
    public string dm_status_jenis_kredit_pembiayaan { get; set; }
    public string dm_status_aktif { get; set; }
    public string dm_status_delete { get; set; }
    public string dm_create_date { get; set; }
    public string dm_update_date { get; set; }
    public string dm_reference_date { get; set; }
}

}