namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class RptGrid_Param
{
    public long rgpr_id { get; set; }
    public long rg_id { get; set; }
    public string rgpr_kode { get; set; }
    public string rgpr_nama { get; set; }
    public string rgpr_catatan { get; set; }
    public string rgpr_datatype { get; set; }
    public string rgpr_controltype { get; set; }
    public Nullable<bool> rgpr_allow_null { get; set; }
    public string rgpr_null_text { get; set; }
    public string rgpr_value_default { get; set; }
    public string rgpr_value_csv { get; set; }
    public string rgpr_value_query { get; set; }
    public string stsrc { get; set; }
    public string created_by { get; set; }
    public Nullable<System.DateTime> date_created { get; set; }
    public string modified_by { get; set; }
    public Nullable<System.DateTime> date_modified { get; set; }

    public virtual RptGrid RptGrid { get; set; }
}

}