namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class RptGrid_RoleSetting
{
    public long rgrole_id { get; set; }
    public long rg_id { get; set; }
    public Nullable<long> role_id { get; set; }
    public Nullable<long> satker_id { get; set; }
    public string stsrc { get; set; }
    public string created_by { get; set; }
    public Nullable<System.DateTime> date_created { get; set; }
    public string modified_by { get; set; }
    public Nullable<System.DateTime> date_modified { get; set; }

    public virtual FWRefRole FWRefRole { get; set; }
}

}