namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class RptGrid
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public RptGrid()
    {
        this.RptGrid_Param = new HashSet<RptGrid_Param>();
        this.RptGrid_Queue = new HashSet<RptGrid_Queue>();
        this.RptGrid1 = new HashSet<RptGrid>();
    }

    public long rg_id { get; set; }
    public Nullable<long> parent_id { get; set; }
    public string rg_nama { get; set; }
    public string rg_catatan { get; set; }
    public string rg_kode { get; set; }
    public string rg_tipe { get; set; }
    public string rg_db_name { get; set; }
    public string rg_query { get; set; }
    public string rg_entrier { get; set; }
    public bool rg_rolesetting_inherited { get; set; }
    public int rg_timeout { get; set; }
    public string stsrc { get; set; }
    public string created_by { get; set; }
    public Nullable<System.DateTime> date_created { get; set; }
    public string modified_by { get; set; }
    public Nullable<System.DateTime> date_modified { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<RptGrid_Param> RptGrid_Param { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<RptGrid_Queue> RptGrid_Queue { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<RptGrid> RptGrid1 { get; set; }
    public virtual RptGrid RptGrid2 { get; set; }
}

}