namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class src_sid
{
    public System.DateTime dm_periode { get; set; }
    public long rowid { get; set; }
    public string sid { get; set; }
    public string nama_sid { get; set; }
    public string system { get; set; }
}

}