namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class TableauLink
{
    public int id { get; set; }
    public string name { get; set; }
    public string type { get; set; }
    public string link { get; set; }
    public string stsrc { get; set; }
    public string created_by { get; set; }
    public string modified_by { get; set; }
    public Nullable<System.DateTime> date_created { get; set; }
    public Nullable<System.DateTime> date_modified { get; set; }
    public Nullable<System.DateTime> date_update { get; set; }
}

}