namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class vw_JarakAntarAktivitas
{
    public long rowid { get; set; }
    public System.DateTime periode { get; set; }
    public string LJK { get; set; }
    public string member_type_code { get; set; }
    public string member_code { get; set; }
    public Nullable<float> user_id { get; set; }
    public Nullable<long> act_count { get; set; }
    public Nullable<double> mean_diff { get; set; }
    public string status_avg_activity { get; set; }
    public string status { get; set; }
}

}