namespace BDA.DataModel
{//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class vw_ListUser
{
    public string UserId { get; set; }
    public string UserNama { get; set; }
    public string UserAlamat { get; set; }
    public string UserTelp { get; set; }
    public string UserEmail { get; set; }
    public Nullable<bool> user_is_notifredalert { get; set; }
    public Nullable<bool> user_is_notifyellowalert { get; set; }
    public string RoleName { get; set; }
}

}